### ISSUE TITLE
Embed the new icon in nsxiv

### ISSUE THREAD

**Issue by XPhyro** [nsxiv/nsxiv#104]
Currently, `data.h` uses the old icon. We should either build a new `data.h` or rework the icon system.

See #1 and #26 for the previous discussions.

**Comment by mamg22** [comment]
I'd like to give this a try, I've been ~~procrastinating~~ tinkering and figuring out the format and compression used for `data.h`. I might be able to generate a new `data.h` from the new PNG icons.

**Comment by mamg22** [comment]
An update on this, I have written a small C program (`img2data`) that generates a new `data.h` from the icons passed as argument, and uses imlib2 so there's no added dependencies. This would allow anyone to customize their nsxiv window icon.

There's two things I'd like to get some opinion or suggestions before creating a PR:

1. `img2data` currently outputs a whole `data.h` replacement, including the declaration for `icon_data_t` and header guards. Is this a good solution? I think there can be a template file which is completed with the generated data, or maybe `#include` the generated data into a `data.h` which only has the guards and struct declaration.

 2. I'm still not quite sure is how to integrate into the build system:

* Should `data.h` be removed from the source and instead be generated when building like an object file? And of course, `img2data` would get compiled as a dependency for generating `icon/data.h`. (I prefer this approach)
* Same as above, but keeping `data.h` in the source tree and generating when changing the icon files.
* Or, should a new `data.h` with the current nsxiv icon be created and leave `img2data.c` there for future logo changes or people who want to customize their window icons (kind of like what muennich did with that awk script, though it only did half the job).

**Comment by N-R-K** [comment]
@mamg22 I think you should just create the PR and mark it as draft. It's much easier to discuss this type of stuff with the code visible.

**Comment by mamg22** [comment]
Opened draft PR #163.
