### ISSUE TITLE
Svg support

### ISSUE THREAD

**Issue by LamprosPitsillos** [nsxiv/nsxiv#122]
Will SVG support come to nsxiv ? 
Reading the project scope I think it is pretty reasonable feature too add that has already been implemented ( although not fully ) in other forks.

**Comment by N-R-K** [comment]
Support request for new image format should go into imlib2. Svg is weird because it's vector graphics and not raster.

> has already been implemented ( although not fully ) in other forks.

I've looked at the svg PR at sxiv and it's quite invasive. It also adds extra dep without compile time switch to disable it.

**Comment by N-R-K** [comment]
Btw, there's an open feature request on Imlib2's issue tracker about svg support. Though I'm not sure what the status of it is. Feel free to bump the issue and/or ask what their plans are for it: https://phab.enlightenment.org/T6743

**Comment by N-R-K** [comment]
Closing, see: #192

**Comment by N-R-K** [comment]
Imlib2 v1.8.0 was released two days ago which adds support for svg images. https://sourceforge.net/p/enlightenment/mailman/message/37605728/
