### ISSUE TITLE
All keys stop working on alternate X keyboard layout

### ISSUE THREAD

**Issue by mamg22** [nsxiv/nsxiv#149]
I checked out the current master version (at commit `d0b5005`) to test out, and I couldn't get any keys to work (such as `q` to quit), but the program seems to work fine, since it closes when requested by the window manager and resizes when window size changes. All of this while using the alternate keyboard layout.

However, when I changed my keyboard layout back to the main one (I use `latam` as main, with `us` as alternate), every key worked properly. If I switch back to the alternate layout, keys still don't work.

I've tracked down the issue to commit `3234b0e`, just after the release of v27.1.

All of these have been tested on a clean build with a default `config.h` copied straight from `config.def.h`.

How to reproduce:

Set keyboard layouts with:

```sh
setxkbmap -layout latam,us -variant ,altgr-intl -option -option grp:ctrls_toggle -option caps:swapescape
```

Switch to alternate keyboard layout (press both Ctrl keys), run nsxiv with any image and try to do anything with the keys (such as zoom or quit).

**Comment by N-R-K** [comment]
@mamg22 thanks for testing it out and reporting. Can you apply this in your `config.h` and see if that fixes the issue?

```c
static const int ignore_mask = LockMask | Mod2Mask | Mod3Mask | Mod4Mask | Mod5Mask;
```

**Comment by N-R-K** [comment]
#150 should fix it.

**Comment by mamg22** [comment]
@N-R-K I've applied that to `config.h`, didn't work. I'll check with #150

**Comment by N-R-K** [comment]
@mamg22 I've check the reproduction steps you've described here and it works for me: 
```sh
setxkbmap -layout latam,us -variant ,altgr-intl -option -option grp:ctrls_toggle -option caps:swapescape
```

**Comment by eylles** [comment]
i can reproduce the problem on my end, i use multiple keyboard layouts but didn't notice this earlier as i use latam, ru(phonetic) and gr, since every binding in nsxiv is done with the latin alphabet i simply assumed that the keystrokes on the non latin alphabet layouts would do nothing since they are symbols from a different alphabet, will proceed to test #150 to see if it fixes it.

**Comment by mamg22** [comment]
After some more testing on `d0b5005` (and master too), on a completely default build, it seems Scroll Up/Down also stop working on alternate keyboard layouts (didn't notice on the initial report because I don't use them that much), Button{1..3} seem to work fine. Reproduction steps are the same.

Applying #150 also fixes the issue.
