### ISSUE TITLE
Errors when compiling with nsxiv-extra/CUSTOMIZATION.md custom function

### ISSUE THREAD

**Issue by Dupond** [nsxiv/nsxiv#179]
Hello,

With the custom function that is given as an example on [this page](https://github.com/nsxiv/nsxiv-extra/blob/master/CUSTOMIZATION.md) I have many compilation errors:

> Dans le fichier inclus depuis main.c:23:
> config.h:114:9: attention: accolades autour d'une initialisation d'un scalaire
>   114 |         { ControlMask,  XK_t,             {g_send_to_kh_ctrl},  XK_t },
>       |         ^
> config.h:114:9: note: (près de l'initialisation de « keys[4].cmd.func »)
> config.h:105:49: attention: trop d'éléments dans l'initialisation d'un scalaire
>   105 | #define g_send_to_kh_ctrl { cg_send_to_kh_ctrl, MODE_ALL }
>       |                                                 ^~~~~~~~
> config.h:114:44: note: dans l'expansion de la macro « g_send_to_kh_ctrl »
>   114 |         { ControlMask,  XK_t,             {g_send_to_kh_ctrl},  XK_t },
>       |                                            ^~~~~~~~~~~~~~~~~
> config.h:105:49: note: (près de l'initialisation de « keys[4].cmd.func »)
>   105 | #define g_send_to_kh_ctrl { cg_send_to_kh_ctrl, MODE_ALL }
>       |                                                 ^~~~~~~~
> config.h:114:44: note: dans l'expansion de la macro « g_send_to_kh_ctrl »
>   114 |         { ControlMask,  XK_t,             {g_send_to_kh_ctrl},  XK_t },
>       |                                            ^~~~~~~~~~~~~~~~~
> config.h:115:9: attention: accolades autour d'une initialisation d'un scalaire
>   115 |         { ControlMask,  XK_c,             {g_send_to_kh_ctrl},  XK_c },
>       |         ^
> config.h:115:9: note: (près de l'initialisation de « keys[5].cmd.func »)
> config.h:105:49: attention: trop d'éléments dans l'initialisation d'un scalaire
>   105 | #define g_send_to_kh_ctrl { cg_send_to_kh_ctrl, MODE_ALL }
>       |                                                 ^~~~~~~~
> config.h:115:44: note: dans l'expansion de la macro « g_send_to_kh_ctrl »
>   115 |         { ControlMask,  XK_c,             {g_send_to_kh_ctrl},  XK_c },
>       |                                            ^~~~~~~~~~~~~~~~~
> config.h:105:49: note: (près de l'initialisation de « keys[5].cmd.func »)
>   105 | #define g_send_to_kh_ctrl { cg_send_to_kh_ctrl, MODE_ALL }
>       |                                                 ^~~~~~~~
> config.h:115:44: note: dans l'expansion de la macro « g_send_to_kh_ctrl »
>   115 |         { ControlMask,  XK_c,             {g_send_to_kh_ctrl},  XK_c },
>       |                                            ^~~~~~~~~~~~~~~~~
> config.h:116:44: erreur: « send_to_kh » non déclaré ici (hors de toute fonction); vouliez-vous utiliser « g_send_to_kh » ?
>   116 |         { 0,            XK_i,             {send_to_kh},         XK_i },
>       |                                            ^~~~~~~~~~
>       |                                            g_send_to_kh
> config.h:124:9: attention: accolades autour d'une initialisation d'un scalaire
>   124 |         { ControlMask,  XK_Delete,        {g_send_to_kh_ctrl},  XK_Delete },
>       |         ^
> config.h:124:9: note: (près de l'initialisation de « keys[14].cmd.func »)
> config.h:105:49: attention: trop d'éléments dans l'initialisation d'un scalaire
>   105 | #define g_send_to_kh_ctrl { cg_send_to_kh_ctrl, MODE_ALL }
>       |                                                 ^~~~~~~~
> config.h:124:44: note: dans l'expansion de la macro « g_send_to_kh_ctrl »
>   124 |         { ControlMask,  XK_Delete,        {g_send_to_kh_ctrl},  XK_Delete },
>       |                                            ^~~~~~~~~~~~~~~~~
> config.h:105:49: note: (près de l'initialisation de « keys[14].cmd.func »)
>   105 | #define g_send_to_kh_ctrl { cg_send_to_kh_ctrl, MODE_ALL }
>       |                                                 ^~~~~~~~
> config.h:124:44: note: dans l'expansion de la macro « g_send_to_kh_ctrl »
>   124 |         { ControlMask,  XK_Delete,        {g_send_to_kh_ctrl},  XK_Delete },
>       |                                            ^~~~~~~~~~~~~~~~~
> config.h:181:9: attention: accolades autour d'une initialisation d'un scalaire
>   181 |         { ControlMask,  XK_L,             {g_send_to_kh_ctrl},  XK_L },
>       |         ^
> config.h:181:9: note: (près de l'initialisation de « keys[69].cmd.func »)
> config.h:105:49: attention: trop d'éléments dans l'initialisation d'un scalaire
>   105 | #define g_send_to_kh_ctrl { cg_send_to_kh_ctrl, MODE_ALL }
>       |                                                 ^~~~~~~~
> config.h:181:44: note: dans l'expansion de la macro « g_send_to_kh_ctrl »
>   181 |         { ControlMask,  XK_L,             {g_send_to_kh_ctrl},  XK_L },
>       |                                            ^~~~~~~~~~~~~~~~~
> config.h:105:49: note: (près de l'initialisation de « keys[69].cmd.func »)
>   105 | #define g_send_to_kh_ctrl { cg_send_to_kh_ctrl, MODE_ALL }
>       |                                                 ^~~~~~~~
> config.h:181:44: note: dans l'expansion de la macro « g_send_to_kh_ctrl »
>   181 |         { ControlMask,  XK_L,             {g_send_to_kh_ctrl},  XK_L },
>       |                                            ^~~~~~~~~~~~~~~~~
> config.h:182:9: attention: accolades autour d'une initialisation d'un scalaire
>   182 |         { ControlMask,  XK_R,             {g_send_to_kh_ctrl},  XK_R },
>       |         ^
> config.h:182:9: note: (près de l'initialisation de « keys[70].cmd.func »)
> config.h:105:49: attention: trop d'éléments dans l'initialisation d'un scalaire
>   105 | #define g_send_to_kh_ctrl { cg_send_to_kh_ctrl, MODE_ALL }
>       |                                                 ^~~~~~~~
> config.h:182:44: note: dans l'expansion de la macro « g_send_to_kh_ctrl »
>   182 |         { ControlMask,  XK_R,             {g_send_to_kh_ctrl},  XK_R },
>       |                                            ^~~~~~~~~~~~~~~~~
> config.h:105:49: note: (près de l'initialisation de « keys[70].cmd.func »)
>   105 | #define g_send_to_kh_ctrl { cg_send_to_kh_ctrl, MODE_ALL }
>       |                                                 ^~~~~~~~
> config.h:182:44: note: dans l'expansion de la macro « g_send_to_kh_ctrl »
>   182 |         { ControlMask,  XK_R,             {g_send_to_kh_ctrl},  XK_R },
>       |                                            ^~~~~~~~~~~~~~~~~
> config.h:184:9: attention: accolades autour d'une initialisation d'un scalaire
>   184 |         { ControlMask,  XK_bar,           {g_send_to_kh_ctrl},  XK_bar },
>       |         ^
> config.h:184:9: note: (près de l'initialisation de « keys[72].cmd.func »)
> config.h:105:49: attention: trop d'éléments dans l'initialisation d'un scalaire
>   105 | #define g_send_to_kh_ctrl { cg_send_to_kh_ctrl, MODE_ALL }
>       |                                                 ^~~~~~~~
> config.h:184:44: note: dans l'expansion de la macro « g_send_to_kh_ctrl »
>   184 |         { ControlMask,  XK_bar,           {g_send_to_kh_ctrl},  XK_bar },
>       |                                            ^~~~~~~~~~~~~~~~~
> config.h:105:49: note: (près de l'initialisation de « keys[72].cmd.func »)
>   105 | #define g_send_to_kh_ctrl { cg_send_to_kh_ctrl, MODE_ALL }
>       |                                                 ^~~~~~~~
> config.h:184:44: note: dans l'expansion de la macro « g_send_to_kh_ctrl »
>   184 |         { ControlMask,  XK_bar,           {g_send_to_kh_ctrl},  XK_bar },
>       |                                            ^~~~~~~~~~~~~~~~~
> config.h:186:9: attention: accolades autour d'une initialisation d'un scalaire
>   186 |         { ControlMask,  XK_underscore,    {g_send_to_kh_ctrl},  XK_underscore },
>       |         ^
> config.h:186:9: note: (près de l'initialisation de « keys[74].cmd.func »)
> config.h:105:49: attention: trop d'éléments dans l'initialisation d'un scalaire
>   105 | #define g_send_to_kh_ctrl { cg_send_to_kh_ctrl, MODE_ALL }
>       |                                                 ^~~~~~~~
> config.h:186:44: note: dans l'expansion de la macro « g_send_to_kh_ctrl »
>   186 |         { ControlMask,  XK_underscore,    {g_send_to_kh_ctrl},  XK_underscore },
>       |                                            ^~~~~~~~~~~~~~~~~
> config.h:105:49: note: (près de l'initialisation de « keys[74].cmd.func »)
>   105 | #define g_send_to_kh_ctrl { cg_send_to_kh_ctrl, MODE_ALL }
>       |                                                 ^~~~~~~~
> config.h:186:44: note: dans l'expansion de la macro « g_send_to_kh_ctrl »
>   186 |         { ControlMask,  XK_underscore,    {g_send_to_kh_ctrl},  XK_underscore },
>       |                                            ^~~~~~~~~~~~~~~~~
> make: *** [Makefile:65 : main.o] Erreur 1

Here's the exact code that I use:

```
static void run_key_handler(const char *, unsigned int);
bool cg_send_to_kh(arg_t key)
{
	run_key_handler(XKeysymToString(key), 0);
	return false;
}
#define g_send_to_kh { cg_send_to_kh, MODE_ALL }
bool cg_send_to_kh_ctrl(arg_t key)
{
	run_key_handler(XKeysymToString(key), ControlMask);
	return false;
}
#define g_send_to_kh_ctrl { cg_send_to_kh_ctrl, MODE_ALL }
```

Removing the lines `#define g_send_to_kh { cg_send_to_kh, MODE_ALL }` and `#define g_send_to_kh_ctrl { cg_send_to_kh_ctrl, MODE_ALL }` works just fine though.

**Comment by N-R-K** [comment]
The example is fine. You need to adjust your keybindings initialization. The compiler error message should be pointing you towards where the problem is.

**Comment by Dupond** [comment]
Well, I asked precisely because those error messages made no sense to me.

But your answer helped, thank you.
