### ISSUE TITLE
animated webp no longer works

### ISSUE THREAD

**Issue by lucas-mior** [nsxiv/nsxiv#189]
It seems to me that `eccd7de` broke animated webp:

```
nsxiv: /home/lucas/imagens/00teste/jabba.webp: Error opening image
nsxiv: no more files to display, aborting
```

regular webp files work just fine...

**Comment by lucas-mior** [comment]
Went to read the diff and saw the note that now Imlib2 >= 1.7.5 is required, by bad.
After updating animated webp is working just fine.

**Comment by N-R-K** [comment]
It should still work with older Imlib2 versions on nsxiv v28. On nsxiv git and all future versions Imlib2 v1.7.5 will be required for animated webp.
