### ISSUE TITLE
Manpage missing

### ISSUE THREAD

**Issue by Hund** [nsxiv/nsxiv#190]
I'm using version 28 from the Arch User Repo and I'm missing the manual pages for nsxiv:

```
$ man nsxiv
env: ‘man’: No such file or directory
```

I checked the `pkgbuild` and there's nothing obvious there disabling the inclusion of any manpages.

The README.md on this GitHub page states that it should be available:

>Please see man page for information on how to use nsxiv. To do so, execute the following after the installation:
>
>$ man nsxiv

What's wrong?

**Comment by mamg22** [comment]
Are you able to read other man pages? Because the error seems to come from something (your shell or some script in the way) not being able to find `man`, and not from `man` itself complaining it cannot find the man page.

**Comment by Hund** [comment]
You're right. I was missing the package `man-db` in my brand new installation with Arch Linux. I can't rember having to install that package myself before.

Thanks! :)
