### ISSUE TITLE
Ability to select part of the image?

### ISSUE THREAD

**Issue by Dupond** [nsxiv/nsxiv#196]
This feature had been suggested on [the sxiv repository](https://github.com/muennich/sxiv/issues/147). Here was muennich's answer:

> I've just coded an experimental selection mechanism and it pretty quickly became clear that a simple solution is not really useful. One would expect to be able to modify the current selection and that the image would scroll whenever the cursor leaves the window while selecting. I think that such a selection mechanism is too much to ask for in sxiv.

I think a selection tool would be useful in many ways:

- it allows to measure a portion of the image, in pixels (for example: how wide is this border on my screenshot?)
- it allows to check if several elements of an image are aligned, just by drawing a selection over the image;
- like the original poster said, it would allow to apply actions in the key-handler to portions of the image.

What are your thoughts about this feature? Would it be something that you could consider adding to nsxiv?

**Comment by N-R-K** [comment]
Just wondering, how will this even work with keyboard?

(n)sxiv isn't keyboard exclusive, but it's very clearly keyboard driven. I don't think there exists any action that can be done via mouse but not via keyboard. On the other hand, there's plenty of things that can be done via keyboard but not via mouse.

**Comment by Dupond** [comment]
Well, there are some scripts for [the mpv media player](https://github.com/mpv-player/mpv) that does that, for example [the crop.lua script on this page](https://github.com/occivink/mpv-scripts).

I've made a few screenshots to show you: when you hit a key, it starts displaying the position of the mouse pointer in the image, like in [the screenshot n°1](https://0x0.st/orX8.png).

Then when you hit the "Enter" key, it starts selecting; you then have the ability to move the mouse pointer thanks to the arrow keys and draw the selection, showing the size of the selection, like in [the screenshot n°2](https://0x0.st/orXZ.png). As you can see, when you start drawing the selection, the part of the image that is not selected is more dark. When you use the arrow keys, the pointer moves by steps of 30 pixels (a mouse would then be required for a more granular selection).

If you press the "Enter" key again, the selection is validated, whereas it's canceled with the "Escape" key.

What do you think of it?

**Comment by N-R-K** [comment]
> What do you think of it?

It can be done, sure. But it seems pretty clunky (keyboard part).

> * it allows to measure a portion of the image, in pixels (for example: how wide is this border on my screenshot?)
> * it allows to check if several elements of an image are aligned, just by drawing a selection over the image;

These can be done via [slop](https://github.com/naelstrof/slop)

> * like the original poster said, it would allow to apply actions in the key-handler to portions of the image.

IMO this is better done via opening the image on an actual editor (via keyhandler).

- - -

Overall I'm not entirely convinced, but I'm open towards reviewing a PR if someone wants to implement it.

**Comment by Dupond** [comment]
It's been more than a month, and no one has expressed any interest about this feature. nsxiv is awesome because of its simplicity; I don't think it's good to add some features for one user only (even it this user is me...) and @N-R-K has pointed me to great solutions. So I close this issue.

Thanx for your answer, and for all your work with nsxiv!
