### ISSUE TITLE
How to Change Cache Size?

### ISSUE THREAD

**Issue by Amarakon55** [nsxiv/nsxiv#205]
Here is a line in config.h:
static const int CACHE_SIZE = 4 * 1024 * 1024; /* 4MiB */

There was a comment above it that said it is recommended to set it to 128MiB. This syntax is confusing for me, how do I set it to 128MiB?

**Comment by N-R-K** [comment]
Simply change the `4` to your desired value. The cache size is set in bytes, multiplying it by 1024 once gives kilobytes and then multiplying by 1024 again gives megabyte. In other words `128 * 1024 * 1024 == 128MiB`.
