### ISSUE TITLE
Xresources "globbing" not working

### ISSUE THREAD

**Issue by smthjhn** [nsxiv/nsxiv#209]
I edited my .Xresources file and added ` *font:		xft:Misc Tamsyn:pixelsize=16:antialias=false:autohint=false`. However it is not being used by sxiv. I also tried a different fonts like cozette-otb from the AUR, Terminus, and Iosevka but nothing changes. Meanwhile, the changes that I made to the font in .Xresources applied to xterm.

I'm using Arch Linux and installed nsxiv from source.

EDIT: I just had to remove `xft:`. It works now.

**Comment by N-R-K** [comment]
The following works for me: `Nsxiv.bar.font: Tamzen:pixelsize=16:antialias=false:autohint=false`

**Comment by eylles** [comment]
`*font:` should work, the .xresources config "architecture" is class based and elements should be capable of using that kind of "globbing", tho this may be a weird edge case where the `*font:` glob doesn't manage to match with `*.font:` at least for nsxiv.

@smthjhn does using `*.font:` make nsxiv pick the font?

**Comment by eylles** [comment]
Ah wait, nevermind just noticed the usage of `xft:` iirc thatis a nonstandar property, usually used by programs that can be specified more than one font through xresources like urxvt and i think st with the font2 patch, from what i remember programs that can only use "1 font" fail to recognize that syntax, a classic example being `xterm`.

@N-R-K maybe we should clarify that in the manual ?

**Comment by N-R-K** [comment]
> *font: should work, the .xresources config "architecture" is class based and elements should be capable of using that kind of "globbing", tho this may be a weird edge case where the *font: glob doesn't manage to match with *.font: at least for nsxiv.
> 
> @smthjhn does using *.font: make nsxiv pick the font?

None of the following works for me:

* `*font:`
* `*.font:`
* `*.*.font:`
* `Nsxiv*bar*font:`

The only way i got it working was by specifying the entire thing: `Nsxiv.bar.font`

**Comment by N-R-K** [comment]
Nevermind, `*font:` works fine. Error was on my end, I was using `xrdb -merge` instead of just `xrdb` when updating my xresources.
