### ISSUE TITLE
Thumbnail caching too slow on directories with large files in them

### ISSUE THREAD

**Issue by duarm** [nsxiv/nsxiv#218]
just opened nsxiv in thumbnail mode in a folder with 100 images, more or less, and the UI got stuck for about 20 seconds while caching the thumbnails, can't this be done asynchronously?

**Comment by N-R-K** [comment]
I think it should already happen "in the background" https://github.com/nsxiv/nsxiv/commit/47af0dd7b5e154fb64d8b4d6c5302ba905055799 . It generates thumbnails if there's no pending X events.

>  in a folder with 100 images

What is the largest image in there, in terms of resolution?

**Comment by duarm** [comment]
there's an 1875x4103 image there, and multiples 1920x1080 and 3000x2000, I thought it had something to do with caching since it shows "Caching x" and "Loading x" in the statusbar, and it occurs only the first time I open nsxiv there

**Comment by N-R-K** [comment]
> there's a 1875x4103 image there

Can you move that image into it's own directory and try again with just that image? I guess it's possible (though seems unlikely) that generating the thumbnail for that single image takes 20s on your system which ended up causing the block.

If that's not it then I think I'm misunderstanding something about how the thumbnail generation works (possible, since I haven't poked around much into the thumbnail related codes).

**Comment by 0ion9** [comment]
AFAIK it is asynchronous. 20 second delays.. I get that if its referencing an external HDD that has to wind up. Oh, and videos. if videos are in the filelist for some reason, I've gotten big delays from that.

OP, you say it 'hangs'. Does the number next to 'caching' go up during this time, or not? If it does go up, I suggest making an effort to definitively rule out the above situations.

**Comment by N-R-K** [comment]
> That depends on imlib2, we don't have control over the loading process.

Also, what Imlib2 version are you on? Because I think there was an issue with an older version of Imlib2 where a loader wasn't doing signature check and reading the entire file.

**Comment by duarm** [comment]
I'm on 1.7.5-1, my keypresses are still computed, once the UI unfreezes, the selected image frame warps to the place corresponding to my keypresses while stuck.

> ui getting blocked is if generating a single thumbnail ends up taking too long.

probably what's happening, but the UI shouldn't block because a single nor multiples thumbnails are taking too long i think

**Comment by 0ion9** [comment]
AFAICS the real thrust of this issue would then boil down to *threaded* caching. Alternatively imlib would need to develop a streaming interface for loading. As I understand it doesn't currently have one, so we cannot load 'part of an image' and poll input without having separate threads.

AFAICS nsxiv is already asynchronous.

**Comment by N-R-K** [comment]
> the UI shouldn't block because a single or multiple thumbnails are taking too long i think

It can block if a single file takes too long. But shouldn't for multiple, we check for pending X events before caching each thumbnail.

**Comment by duarm** [comment]
sorry for the late response
>  this issue would then boil down to threaded caching

exactly, we need a threaded caching, the caching should occur in the background and never block the UI.

>> There's a bunch of videos there, shouldn't those just be ignored?

>That depends on imlib2, we don't have control over the loading process.

not related but this is so silly, opening sxiv in a folder with 1 image and 20 videos takes forever, when those should just be ignored, if nothing can be done from the sxiv side of things, i'm amazed how the imlib guys let this one slip through.

**Comment by N-R-K** [comment]
> exactly, we need a threaded caching, the caching should occur in the background and never block the UI.

I'm not sure if we want to introduce multi-threading into nsxiv, especially when the problem seems to related to videos.

> nothing can be done about it? opening sxiv in a folder with 1 image and 20 videos takes forever, when those should just be ignored, the workaround is to simply alias sxiv to "sxiv *.jpg *.png *.bmp".

It *should* be ignored (atleast on newer Imlib2 versions which fixes the bug), but the loaders still need to read the first couple bytes to verify signature. For example there might be a `png` file with `.webm` extension.

---

@duarm Can you try again with nsxiv's `-p` flag? I'm wondering weather the bottleneck is reading the files or writing them. Since on my system (even on my secondary HDD) I cannot reproduce this.

**Comment by N-R-K** [comment]
> I'm wondering weather the bottleneck is reading the files or writing them.

Ahh wait, the video files should just be ignored after failed signature check. So writing shouldn't even happen.

**Comment by N-R-K** [comment]
Ok, I think I found the problem. Can you move the `xpm` loader out of the imlib2 loader's directory (see the last 2 paragraph on this comment on how to do that https://github.com/nsxiv/nsxiv/issues/218#issuecomment-1035257073 ) and report back? @duarm

**Comment by duarm** [comment]
> Can you move the xpm

this works, indeed 99% of the time was due to this, I can now open sxiv on the same folder I mentioned at the beggining without any noticeable hanging.

**Comment by N-R-K** [comment]
I assume not many people deal with XPM, so as a temp workaround until new imlib2 is released and your distro ships it, moving the xpm loader out should work.

**Comment by N-R-K** [comment]
pinning this until new imlib2 version is released, in case someone else runs into this since opening a directory is a rather common use case.

**Comment by XPhyro** [comment]
Unpinning in favour of #242.
