### ISSUE TITLE
Feature proposal: Touchscreen (gestures) support

### ISSUE THREAD

**Issue by KaiJan57** [nsxiv/nsxiv#219]
Users with touchscreen-enabled devices such as tablets or convertible laptops will profit a lot even from basic touchscreen support, as seen in minimalist software like pwmt's zathura document viewer, which allows for dragging zoomed in content.
As far as I could tell there is no easy way to script this functionality; concerning dependencies I am not sure, but I guess it can't be too bad if zathura has it.

EDIT: touchscreen dragging can be enabled by remapping i_drag to button 1 in config.h, but scrolling inertia and pinch-to-zoom is not implemented yet.

**Comment by N-R-K** [comment]
> Users with touchscreen-enabled devices such as tablets or convertible laptops

Hmm, I don't use such devices, can they simulate all mouse events? Because nsxiv supports all basic operation via mouse, e.g scroll up/down will zoom in/out.

**Comment by KaiJan57** [comment]
They can, but nsxiv doesn't let me drag a zoomed-in picture using mouse, touchpad or touchscreen. Pinch-to-zoom gestures (multi-touch in general) certainly need extra handling, but that is not available in zathura either…

**Comment by N-R-K** [comment]
> can this default behavior be remapped to pan without pressing buttons?

You can change it in *config.h*. If you're asking for the default to be changed, then that's unfortunately not going to happen. We can't change any sxiv defaults: https://github.com/nsxiv/nsxiv/blob/master/CONTRIBUTING.md#project-scope

**Comment by KaiJan57** [comment]
Thank you, it worked! But this way, there is no scrolling inertia with touch input and config.h doesn't seem to have switches for that, does it? Besides that I noticed that panning is a bit laggy/jerky (at least on my computer), which makes it less comfortable to use with touch…

**Comment by N-R-K** [comment]
> Besides that I noticed that panning is a bit laggy/jerky

I'm not noticing any lag on my end. Jerky-ness *could* be due to it being to sensitive small mouse movements, not sure though. Could be something else.

**Comment by KaiJan57** [comment]
Yeah, maybe it depends on available computing power and image size… I'm experiencing it worse with larger pictures, especially when greater than 100 MB, but it's not a real issue. Probably would be best to keep this issue focused on touchscreen gestures, just as the title suggests :)
