### ISSUE TITLE
Smaller icons

### ISSUE THREAD

**Issue by DNDEBUG** [nsxiv/nsxiv#222]
[icons.zip](https://github.com/nsxiv/nsxiv/files/8097197/icons.zip)

**Comment by N-R-K** [comment]
Hmm, the icons are already quite small. And merging this will probably end up increasing the git repo size because git isn't good at binary files https://github.com/muennich/sxiv/pull/183#issuecomment-61401816

**Comment by DNDEBUG** [comment]
i worked 73 hours to make it smaller /s
:sob:

**Comment by eylles** [comment]
lol wut?

**Comment by eylles** [comment]
@DNDEBUG got a reproducible process for optimizing the icons like u did? If so we may add that as a script for building the icons

**Comment by DNDEBUG** [comment]
> @DNDEBUG got a reproducible process for optimizing the icons like u did? If so we may add that as a script for building the icons

https://github.com/JayXon/Leanify

leanify -i "Insert big number here" -p *.png
:3

**Comment by N-R-K** [comment]
> If so we may add that as a script for building the icons

Don't really think there's any need to add extra dep for something that's already quite small.
