### ISSUE TITLE
Add an INSTALL variable to the Makefile

### ISSUE THREAD

**Issue by xfgusta** [nsxiv/nsxiv#223]
This is useful to [packagers](https://docs.fedoraproject.org/en-US/packaging-guidelines/#_timestamps) who may wish to set `INSTALL='install -p'` (on Fedora Linux, it's automatically set with the `%make_install` macro) in order to preserve timestamps from the source tarball. I know that `cp -p` would do the job, but by using `install` we can also set the file permission instead of invoking `cp` followed by `chmod`.

I have made a patch to use `install` instead of `cp`/`chmod`, but I'd like to hear from you about the change before opening a PR.

**Comment by N-R-K** [comment]
Hi, we're not using anything non-POSIX on the Makefile (excluding `?=` and `+=`). `install` is non-POSIX so we're not going to add that.

I would suggest patching it for your package, the Makefile is not going to change much so there shouldn't be conflict on upgrade.

**Comment by xfgusta** [comment]
Thanks for the reply!

**Comment by N-R-K** [comment]
No problem! And in case we *do* make any significant change to the Makefile, they'll be documented in `CHANGELOG` upon release.
