### ISSUE TITLE
Feature Wish: dmenu mode in main branch

### ISSUE THREAD

**Issue by Rentib** [nsxiv/nsxiv#226]
I feel like dmenu patch is a great addon which can be useful in many situations.
I do understand that primary focus of nsxiv is viewing images, but adding such functionality would without a doubt add more room for creating scripts.
Dmenu patch is secondary and so it doesn’t see improvements as often and can easily become obsolete.

**Comment by TAAPArthur** [comment]
Was going to let someone else respond, but don't want to keep leaving you hanging. The short answer is no. At least not here as you describe. We don't plan to do major refactoring so it may be possible that the patch will just continue to work or would only require minor updates.

If you are still concerned there are things we could do to make extensions easier/patches more stable. Keep in mind these aren't goals of the project. I'd suggest some, but after looking at https://github.com/nsxiv/nsxiv-extra/blob/master/patches/dmenu-mode/dmenu-mode-8f6ba7b.patch, I don't really think you have to worry about the patch breaking in a way that is not easily fixed.

If anything maybe we should add some actions to nsxiv-extra to try an apply the patches after every commit or on version updates so we'd at least know when something breaks (We still wouldn't prevent breaking them). If this satisfies you, then the fastest way to see it implemented is to send a PR.

**Comment by explosion-mental** [comment]
You could just have something like this:
```c
{ 0,            XK_d,             g_toggle_image_mark,  None },
{ 0,            XK_d,             g_quit,               None },
```

**Comment by explosion-mental** [comment]
with `-o` ofc

**Comment by N-R-K** [comment]
> You could just have something like this:
> 
> ```c
> { 0,            XK_d,             g_toggle_image_mark,  None },
> { 0,            XK_d,             g_quit,               None },
> ```

That'll work, but a caveat: if there's previously marked images those will get printed as well.

---

> Do you have any specific script in mind that needs dmenu mode? nsxiv already can print marked images to stdout via `-o`, dmenu mode just makes the printing instant.

Was asking this because currently dmenu mode is more or less just a convenience patch, which makes it less attractive to include in mainline. But there's situations where this would solve a problem that otherwise couldn't have been solved then there might've been more merit for including it on mainline.
