### ISSUE TITLE
Building from non-git source rebuilds `options.o` and `version.h` every time.

### ISSUE THREAD

**Issue by mamg22** [nsxiv/nsxiv#237]
If you run `make` and then `make install` on source extracted from a tarball, you'll see it compiling and linking `options.o` again on `make install`. Could reproduce this with tarballs for v29, v28 and v27.1.

The problem seems to be the lack of  `.git/index` that makes it rebuild `version.h` every time, which in turn triggers a rebuild for `options.c` with a possibly different set of flags or compilation options. 

Noticed this after half of my [Fedora COPR builds](https://copr.fedorainfracloud.org/coprs/mamg22/nsxiv/build/3597497/) failed on newer versions. All the code was built with the proper CFLAGS required by Fedora on the `make CFLAGS=...` phase, but the `make install` rebuilt `options.o` without them, causing it to fail  during linking because everything but that file was compiled with PIC.

**Comment by N-R-K** [comment]
You can patch out the Makefile for now: `sed -i -e '/^install: / s|: all|:|' Makefile`

As for the issue, maybe it would be better to pass the version as a CPPFLAG and just removing version.h all together.

**Comment by N-R-K** [comment]
> Could reproduce this with tarballs for v29, v28 and v27.1.

Curious, how come the older versions did not fail to build if they had same issue?

**Comment by mamg22** [comment]
It worked as long as the second `options.o` build compiled and linked correctly, and for v28 and earlier, if the settings were exported via environment, there wasn't a difference because make picked them up. In my case, it only failed because a few builds were incompatible (PIC vs non-PIC).

**Comment by N-R-K** [comment]
As per the discussion in https://github.com/nsxiv/nsxiv/pull/238, we couldn't come up with an optimal solution. Added this issue to the list of [Known Issues](https://github.com/nsxiv/nsxiv/issues/242) instead.
