### ISSUE TITLE
Navigate to the next/prev image from a different directory

### ISSUE THREAD

**Issue by sudo-nice** [nsxiv/nsxiv#240]
Please, imagine we have these images opened with nsxix. Currently, there is no way to jump from e.g. `1.jpg` to `4.jpg` and then to `7.jpg`, or jump backwards from `9.jpg` to `6.jpg` and then to `3.jpg`, but it might be handy in some scenarios.

```
.
├── 1
│  └── a
│     ├── 1.jpg
│     ├── 2.jpg
│     └── 3.jpg
├── 2
│  └── a
│     ├── 4.jpg
│     ├── 5.jpg
│     └── 6.jpg
└── 3
   └── a
      ├── 7.jpg
      ├── 8.jpg
      └── 9.jpg
```

**Comment by N-R-K** [comment]
Duplicate of https://github.com/nsxiv/nsxiv/issues/207

---

> it might be handy in some scenarios

Can you describe some of these scenarios? One that was mentioned was when using nsxiv to read comics. I'm interested in if there's others.

---

Also one more question, jumping forwards should be straight forward. For example jumping from `2.jpg` would take to `4.jpg`.

But what about jumping backwards? When jumping backwards, let's say from `8.jpg`, do you expect to end up at `6.jpg` (the last entry on that folder) or `4.jpg` (the first entry on that folder) ?

**Comment by N-R-K** [comment]
ping: @fboumol

**Comment by sudo-nice** [comment]
Oh, sorry I didn't find the duplicate.

My scenario is pretty straightforward, imagine we want to skim through a directory with sets of images to find one set we are interested in. My current solution would be to `cd` into every subdirectory and observe the content, but having the feature implemented, I could just send all the images in the tree to nsxiv and navigate inside it, which would be more convenient.

>But what about jumping backwards?

Jumping backwards from `8.jpg` I'd expect to land on `6.jpg`, because it's the first non-sibling image in that direction.

**Comment by N-R-K** [comment]
> Jumping backwards from `8.jpg` I'd expect to land on `6.jpg`, because it's the first non-sibling image in that direction.

I'd expect to land on `4.jpg` instead, since when going back a folder on a filemanager for example, your cursor ends up on the first entry on that folder, not last.

Anyhow, landing on `6.jpg` isn't that bad I guess, and is easier to implement since we don't need to special case backwards jump.

---

Also pointing this out in case you didn't think of it: nsxiv will follow whatever cli arg you give it:

```console
$ nsxiv dir1/*.jpg dir2/*.jpg dir1/*.png dir2/*.png
```

Will load all images in the order given to via cli args. So jumping from `dir1/1.jpg` will take to `dir2/1.jpg` and then `dir1/1.png`.

**Comment by sudo-nice** [comment]
>Anyhow, landing on 6.jpg isn't that bad I guess, and is easier to implement since we don't need to special case backwards jump.

Yes, I suggested it that way mostly because of consistency and simplicity.

>Also pointing this out in case you didn't think of it: nsxiv will follow whatever cli arg you give it

Thank you, I understand that and I since there is nothing surprising with such behavior, it's fine with me. Basically, nsxiv would do exactly what we asked for. :ok_hand:

**Comment by 0ion9** [comment]
Trying to reformulate the problem in a way that is not so specific, two possible paths occur to me:

1. 'sentinel/divider' filenames, which a) serve as waypoints for a 'next/prev' command, and b) cannot be deleted from filelist. Would need a command line option which ideally could accept multiple filenames.
2. Add a 'group' attribute to each filelist item, which would be an 'enumerated' integer. Commands to go to next/prev group, cycle the group value of marked items, and adjust the upper bound of the enumeration would be needed. command line option to set group value for a given range of items in file list. Some visual convention would be needed to show 'group value' in thumbnail view.
3. 'jump markers' / bookmarks. Analogous to current 'mark' concept, but navigation only. 'next/prev' commands and CLI option to set bookmarks needed.
Either approach could support a scripted nsxiv wrapper to achieve 'move by directory' result. 1 is more obvious and suckless, 2 is more dynamic and unintrusive.
3 is minimal but cannot strictly achieve the identification of both ends of a 'run' that was recently discussed.

Personally I have already considered implementing something like 1, as I frequently have a filelist divided in 4-8 categories and include divider images that ID the categories.

**Comment by N-R-K** [comment]
@0ion9 Or maybe just the `filelist-filter` would do. If we export all the file paths and import it back, it should be trivial to export/import the fileidx as well.

So one could just leave the filelist intact and simply change the fileidx in order to change the current image.

**Comment by N-R-K** [comment]
As a temp workaround, you can use this patch: https://github.com/nsxiv/nsxiv/compare/master..N-R-K:patch_next_dir

For a more general solution, you'll need to wait until `filelist-filter` is implemented.

**Comment by sudo-nice** [comment]
Thank you a lot, works like a charm!

**Comment by N-R-K** [comment]
Added the [nav-dir](https://github.com/nsxiv/nsxiv-extra/tree/master/patches/nav-dir) patch to nsxiv-extra.
