### ISSUE TITLE
Cannot open SVG files despite linking against a version of imlib2 that supports them

### ISSUE THREAD

**Issue by dvejmz** [nsxiv/nsxiv#241]
nsxiv version: `nsxiv v29`
imlib2 version: `1.8.0`

Following [this comment](https://github.com/nsxiv/nsxiv/issues/122#issuecomment-1032455255) from @N-R-K, I thought I'd build my own version of nsxiv and link it against imlib2 1.8.0 to enable SVG support.

I downloaded the [imlib2 1.8.0](https://downloads.sourceforge.net/enlightenment/imlib2-1.8.0.tar.xz) release archive, built it and installed it under `/usr/local/lib`.

```
$ ls -l /usr/local/lib
drwxr-xr-x@    - root  6 Mar 19:56 imlib2
.rw-r--r--@ 2.0M root  6 Mar 20:05 libImlib2.a
.rwxr-xr-x@  989 root  6 Mar 20:05 libImlib2.la
lrwxrwxrwx@   18 root  6 Mar 20:05 libImlib2.so -> libImlib2.so.1.8.0
lrwxrwxrwx@   18 root  6 Mar 20:05 libImlib2.so.1 -> libImlib2.so.1.8.0
.rwxr-xr-x@ 1.3M root  6 Mar 20:05 libImlib2.so.1.8.0
drwxr-xr-x@    - root  6 Mar 20:05 pkgconfig
```

I updated my LD cache via `ldconfig` to ensure `/usr/local/lib` was in my linker search path as apparently this is a non-standard location in my distribution.

I then cloned nsxiv, built and installed it. It seems it was able to detect and link against the imlib2 `.so` just fine.

```
$ ldd `which nsxiv`
	linux-vdso.so.1 (0x00007ffdb07f5000)
	libImlib2.so.1 => /usr/local/lib/libImlib2.so.1 (0x00007f4ce22cb000)
	libX11.so.6 => /lib64/libX11.so.6 (0x00007f4ce2183000)
	libexif.so.12 => /lib64/libexif.so.12 (0x00007f4ce2135000)
	[More libs...]
```

I can open non-SVG images just fine but attempting to open an SVG file returns the following error

```
$ nsxiv ~/tmp/plot.svg
nsxiv: /home/dvejmz/tmp/plot.svg: Error opening image
nsxiv: no more files to display, aborting
```

I was expecting I'd be able to open SVG files just fine provided nsxiv was linked against imlib2 1.8.0 but there seems to be something else missing here. Any ideas as to what it could be?

**Comment by N-R-K** [comment]
> I downloaded the [imlib2 1.8.0](https://downloads.sourceforge.net/enlightenment/imlib2-1.8.0.tar.xz) release archive, built it and installed it

How did you install it? If you installed it via running `./configure` first then it won't build loaders for which you don't have the libraries for. Ensure that you have `librsvg` installed, and try compiling and installing imlib2 again.

**Comment by dvejmz** [comment]
That was it! I installed the development libs/headers for `librsvg` (`librsvg2-devel` on Fedora 35), recompiled, reinstalled imlib2 1.8.0 and it worked.

Thanks for the quick reply @N-R-K. Great to see SVG support has finally arrived to imlib2, which will benefit so many applications, including (n)sxiv.
