### ISSUE TITLE
How is the bar height calculated?

### ISSUE THREAD

**Issue by ethanh92** [nsxiv/nsxiv#246]
I'm not a programmer so bear with me.

I want to be able to dynamically calculate the bar height based on font size for a screenshot script I'm writing.

I've looked through the source code and think I've come across the relevant portion

```
 67 #if HAVE_LIBFONTS
 68 static void win_init_font(const win_env_t *e, const char *fontstr)
 69 {
 70    int fontheight = 0;
 71    if ((font = XftFontOpenName(e->dpy, e->scr, fontstr)) == NULL)
 72       error(EXIT_FAILURE, 0, "Error loading font '%s'", fontstr);
 73    fontheight = font->ascent + font->descent;
 74    FcPatternGetDouble(font->pattern, FC_SIZE, 0, &fontsize);
 75    barheight = fontheight + 2 * V_TEXT_PAD;
 76    XftFontClose(e->dpy, font);
 77 }
```

However, I'm having a bit of trouble figuring out how all this works. If I set the font size in Xresources to 11, the bar is 22 pixels high, however, with other numbers such as 20, the bar height ends up being something like 39.

What I'm wondering is how is the bar height calculated based on the font size as configured in xresources using `Nsxiv.bar.font` and how is it calculated by default if `Nsxiv.bar.font` is not set?

Thanks!

**Comment by explosion-mental** [comment]
Hello, always glad if someone is tinkering.

You may have notice this line
```c
barheight = fontheight + 2 * V_TEXT_PAD;
```
`fontheight` is self descriptive. the `2*V_TEXT_PAD` is a little padding that muennich add to the bar so it isn't an **exact** fit but there is 2 pixel padding (`V_TEXT_PAD` value is `1`).

I'm not that familiar with Xresources so i'm not sure how does changing the font size in it werks, but if you **don't** set one in Xresources, from an unmodified source code, it will default to `monospace-8`.

So the bar is calculated by the font height + 2 pixels.

**Comment by explosion-mental** [comment]
> I want to be able to dynamically calculate the bar height based on font size for a screenshot script I'm writing.

Does this means you are 'dynamically' setting a font?
Keep in mind that changes in Xresources don't take effect unless you 'restart', meaning you have to close and re-open the program. Changes in config.h requires you to recompile along with the 'restart'.

**Comment by mamg22** [comment]
> However, I'm having a bit of trouble figuring out how all this works. If I set the font size in Xresources to 11, the bar is 22 pixels high, however, with other numbers such as 20, the bar height ends up being something like 39.

Those font sizes are measured in points, not pixels, leading to the variation you see, see the font names section of [this manual](https://www.freedesktop.org/software/fontconfig/fontconfig-user.html).

Maybe you can use `pixelsize=...` for pixel-based units in font sizes, or figure out the point to pixel ratio of text.

**Comment by N-R-K** [comment]
>I want to be able to dynamically calculate the bar height based on font size for a screenshot script I'm writing.

Curious what exactly this screenshot script is doing.

**Comment by ethanh92** [comment]
> So the bar is calculated by the font height + 2 pixels.

I guess the trouble is then figuring out what the relationship between the font size and the font height is.

One thing that puzzles me is line 73:

```
73    fontheight = font->ascent + font->descent;
```

Maybe related to what I'm seeing up here?

```
37 static XftFont *font;
38 static double fontsize;
```

>Curious what exactly this screenshot script is doing.

I take a screenshot with scrot and then open it in nsxiv at 90% the screen size plus the height of nsxiv's bottom bar on the vertical so that I don't see any background. Right now, the bar hight is hard coded into the portion that calculates the vertical, but I'd like to make this more dynamical and portable in case I want to use it on another machine with a different dpi or font size in the future. For reference:

`HEIGHT=$(( ( $(xdotool getdisplaygeometry | cut --delimiter=' ' --fields=2) * 90 / 100 ) + 22 ))`

**Comment by N-R-K** [comment]
> I guess the trouble is then figuring out what the relationship between the font size and the font height is.

That's not something you'll find on the nsxiv source code. You'll have to look into the Xft documentation I presume.

**Comment by N-R-K** [comment]
> at 90% the screen size plus the height of nsxiv's bottom bar on the vertical so that I don't see any background.

Doesn't the fill mode already do this, `nsxiv -s F img.png` ? Or am I misunderstanding what you're trying to do?

In any case, not really an nsxiv issue on how Xft does point to pixle conversion. Closing.

**Comment by N-R-K** [comment]
> at 90% the screen size plus the height of nsxiv's bottom bar on the vertical so that I don't see any background.

Doesn't the fill mode already do this, `nsxiv -s F img.png` ? Or am I misunderstanding what you're trying to do?

In any case, not really an nsxiv issue on how Xft does point to pixle conversion. Closing.
