### ISSUE TITLE
editorconfig

### ISSUE THREAD

**Issue by eylles** [nsxiv/nsxiv#25]
i'm seeing we constantly have problems with spaces where tabs should be used, and when a conflict is resolved in github it won't be noticed but github will leave spaces intact, ideally we should not have to deal with indenting inconsistencies, which is why i propose we add an editorconfig file to nsxiv in order to enforce the indentation style

https://editorconfig.org/

editorconfig is implemented in multiple git host services and editors, also supported by every popular editor with plugins.

**Comment by GRFreire** [comment]
For some reason, committing #40 did not close this issue automatically... Closing manually then.

**Comment by eylles** [comment]
@GRFreire it isn't auto closing because we are merging to dev, not to master, it confused me too and i closed 2 issues yesterday 😅, when we finally merged dev into master this issue would had been closed.
