### ISSUE TITLE
Fullscreen option causes the window to open on a different monitor

### ISSUE THREAD

**Issue by rakusan2** [nsxiv/nsxiv#257]
I have 3 monitors (built-in + 2 external) and my second monitor is set as the primary
When I run `nsxiv ./image` it opens the window on the monitor with the terminal
When I run `nsxiv -f ./image` it opens on the build-in monitor

Can a `-m` option be added like what `dmenu` has?

OS: Ubuntu 20.04.4

**Comment by N-R-K** [comment]
There was recently some changes to the `-f` flag, which nsxiv version/commit are you on? Run `nsxiv -v` and attach the output.

If you're on latest git then checkout commit e9468d3 and see if that solves your issue.
```console
$ git checkout e9468d3
$ make clean
$ make
$ ./nsxiv -f /path/to/image.png
```

**Comment by rakusan2** [comment]
I had `nsxiv v29-6-g14e9c34` when I opened this and now I have `nsxiv v29-8-gf05165a` (latest master)
Does the same thing
I have then tried going back to the commit specified and also no change

My WM is `GDM 3.36.3`

**Comment by XPhyro** [comment]
Can you check if running `nsxiv ./image` and then toggling fullscreen manually (default key <kbd>f</kbd>) moves the window to the built-in monitor?

**Comment by rakusan2** [comment]
Toggling fullscreen manually has the expected behavior. That being that it does not move the window to a different monitor.

**Comment by XPhyro** [comment]
Does this patch fix the issue?

```diff
diff --git a/window.c b/window.c
index dde9485..b356599 100644
--- a/window.c
+++ b/window.c
@@ -337,12 +337,6 @@ void win_open(win_t *win)
 	hints.initial_state = NormalState;
 	XSetWMHints(win->env.dpy, win->xwin, &hints);
 
-	if (options->fullscreen) {
-		XChangeProperty(e->dpy, win->xwin, atoms[ATOM__NET_WM_STATE],
-		                XA_ATOM, 32, PropModeReplace,
-		                (unsigned char *) &atoms[ATOM__NET_WM_STATE_FULLSCREEN], 1);
-	}
-
 	win->h -= win->bar.h;
 
 	win->buf.w = e->scrw;
@@ -354,6 +348,10 @@ void win_open(win_t *win)
 	XSetWindowBackgroundPixmap(e->dpy, win->xwin, win->buf.pm);
 	XMapWindow(e->dpy, win->xwin);
 	XFlush(e->dpy);
+
+	if (options->fullscreen) {
+		win_toggle_fullscreen(win);
+	}
 }
 
 CLEANUP void win_close(win_t *win)
```

**Comment by N-R-K** [comment]
> Toggling fullscreen manually has the expected behavior. That being that it does not move the window to a different monitor.

That's weird, because that's exactly what was being done at https://github.com/nsxiv/nsxiv/commit/e9468d3d3670ceddbababe312a3523f473159306. It would map the window normally and then fullscreen it.

But you said that going back there didn't help?

>  I have then tried going back to the commit specified and also no change

---

In any case, try to check your window manager settings/config to see if that's any option that can specify where windows which *start in fullscreen mode* go. Because it seems to me that your WM is treating programs that start in fullscreen differently than programs that goes into fullscreen later.

**Comment by N-R-K** [comment]
Closing since no follow up.
