### ISSUE TITLE
`win-title` can slow nsxiv to a crawl with `-a` option when viewing gifs

### ISSUE THREAD

**Issue by defaultxr** [nsxiv/nsxiv#258]
When invoking nsxiv on a gif with the `-a` option like so:

`nsxiv -a test.gif`

And with a `win-title` script in `.config/nsxiv/exec/win-title`, nsxiv can become completely unresponsive if the `win-title` script isn't fast enough. When this is the case, pressing `n`, `p`, `Enter`, etc, no longer do anything. The gif continues to play but it seems like no input is actually processed.

If you change the `win-title` script to something like the following, it seems that `win-title` is being called for every frame of animation:

```bash
#!/bin/bash

echo test $RANDOM >&2
echo nsxiv
```

Then if you run `nsxiv -a test.gif` you will see line after line of `test 3428` and similar, even without issuing any commands to nsxiv.

So it seems that even though nsxiv doesn't pass any information about the animation to the `win-title` script, `win-title` is still being called for every frame of animation. This is pretty inefficient and seems like a bug to me.

**Comment by N-R-K** [comment]
Not a bug, from the manpage:

> The window title can be replaced with the output of a user-provided script, which is called by nsxiv whenever there's a redraw.

We *could* add more argument and pass the animation info to `win-title` in the future. But yes, it's inefficient as it currently is.

**Comment by N-R-K** [comment]
> So it seems that even though nsxiv doesn't pass any information about the animation to the win-title script, win-title is still being called for every frame of animation.

This has been fixed at 810a965.

> nsxiv can become completely unresponsive if the win-title script isn't fast enough.

The script however will still block the UI, proposed fix: #275 .
