### ISSUE TITLE
 Alternative keybinding for i_toggle_animation

### ISSUE THREAD

**Issue by N-R-K** [nsxiv/nsxiv#27]
Reported by @internet-account in https://github.com/muennich/sxiv/issues/443

> Hi,
>
> The default keybinding to toggle gif playback C-Space conflicts with IMEs, like for example ibus.
It's used to switch between different keyboard layouts or input methods, so pressing C-Space doesn't get send to sxiv.
>
> It would be nice if there was a builtin alternative keybinding for i_toggle_animation. Maybe for example C-Enter? Or maybe something else.
>
> { ControlMask, XK_Return, i_toggle_animation, None },

**Comment by eylles** [comment]
How about changing this default keybind to Ctrl-a ? I don't think there's currently anything that uses that binding.

**Comment by N-R-K** [comment]
I wouldn't wanna change default bindings. Also how common is this issue? If it's common enough then I think we can provide another keybinding just so people on binary distros won't need to compile.

But if it's not too common then I think it's upto the few affected people to customize keybinding and compile it themselves. It's not really possible to handle all kind of keybind collusion, we should only try to handle common cases.

**Comment by eylles** [comment]
ibus is used on most desktop environments to manage keyboard layouts and inserion of unicode like emojis, i think the only DEs that don't pull ibus are xfce and lxde/lxqt.

So it is common for anyone that uses a DE, window managers ain't much safer as any program that uses ibus will call and activate it, some of the ones that use ibus are poorly coded so they won't kill ibus when the program is closed.

**Comment by eylles** [comment]
closed by https://github.com/nsxiv/nsxiv/commit/1a922a4c82a3e5e83378d120460a9cfa08794115
