### ISSUE TITLE
Certain GIFs Cause Slideshow to Stop Cycling

### ISSUE THREAD

**Issue by 083750043** [nsxiv/nsxiv#281]
Hello!

I've been using the original SXIV for a digital photo frame for my kids, and it's been working great. However, GIF performance has historically been awful, so I've been playing around with this fork to see if it's any better. And boy, is it ever! 

However, I ran into one issue that I'm hoping that you might have some insight on. There are a few gifs in the directory that I pull from that cause the slideshow/delay function to stop. Most are fine, but when it hits these specific ones, they keep playing indefinitely, instead of cycling to the next one.

I've tried some super basic troubleshooting, (changing filenames, etc.), but am at a bit of a loss.

Examples:
This one works fine, and the slideshow advances as expected:
![panda10](https://user-images.githubusercontent.com/105979165/169654611-b6efc34f-24cd-4db0-b121-b9b89b4eebc1.gif)

This one causes the slideshow to stop advancing, and just plays it endlessly:
![panda12](https://user-images.githubusercontent.com/105979165/169654654-4b7fb912-e7a7-4da2-a980-acb27fc9ffc6.gif)

Thank you!! I super appreciate all the effort in keeping this project alive.

**Comment by N-R-K** [comment]
The way slideshow logic works is that it picks either the slideshow delay, or if the image is animated then it picks the full image animation duration if it's bigger than the slideshow delay.

So for example, if the slideshow delay is `5sec`, and an animated image is `3sec`, it will go to the next image after `5s`. However if the animated image is let's say `7sec` (which is >5sec) it will go to the next image after `7s` and not `5s`.

So if you have a super long gif, that can mess up the slideshow. But the example you posted doesn't seem to be long, and I can't reproduce the issue on my system. It's working fine here, so I suppose there's something else going on here.

Can you post some more examples of images which break the slideshow?

**Comment by N-R-K** [comment]
Also which version of nsxiv are you using, could you post the output of `nsxiv -v` ?

Also how did you test the issue? Can you run `nsxiv -S 3 1.gif 2.gif 3.gif` where 2 is the problem gif and confirm if it's actually the *image itself* that's triggering the bug or not?

**Comment by 083750043** [comment]
Hey thanks for the quick response!

nsxiv version: v29-19-gb4268fb

Also, I should've mentioned in the initial post, that I'm invoking nsxiv with a startup script using the following command:

`nsxiv -afb -s f -S 25 /mnt/frame_media/`

The directory contains a mix of still images, (JPGs and PNGs), and gifs, and it still reliably doesn't progress past the second gif above.

I'll try running your test shortly and see if it triggers it.

Thank you!

**Comment by 083750043** [comment]
Interesting.

So I tried with this command:

`nsxiv -S 3 /mnt/frame_media/test/1.gif /mnt/bframe_media/test/2.gif /mnt/frame_media/test/3.gif`

And it worked, but only displayed one frame. So I added the `-a` flag:

`nsxiv -a -S 3 /mnt/frame_media/test/1.gif /mnt/bframe_media/test/2.gif /mnt/frame_media/test/3.gif`

And it plays the first gif, but doesn't progress beyond that.

**Comment by N-R-K** [comment]
The 2nd file in the 2nd command has a different path. Assuming that was a typo, so the image itself *is* what's triggering the bug... Still can't reproduce it on my system at least. Does it show any error message on the terminal or anything else that could be useful information?

**Comment by 083750043** [comment]
Oops! Sorry, yes, that's a typo.

And no errors at all. Going to try a few things to try and narrow it down.

**Comment by N-R-K** [comment]
Btw, is this something that happens on `nsxiv` only or does it happen on `sxiv` as well? If it also happens on `sxiv` then I'm out of ideas. But if `sxiv` itself works fine and it's an issue introduced in `nsxiv`, then you could try using `git bisect` to find the faulty commit.

**Comment by 083750043** [comment]
Yup! It works perfect with `sxiv`. I wanted to move off to `nsxiv` specifically for gif performance, (which is so, _so_ much better), and this is the only bug I've run into.

I'll give `git bisect` a shot and let you know!

**Comment by 083750043** [comment]
Still working to narrow the issue down to the specific commit, but here's what I've found so far:

- The issue was introduced with the v29 release. It functions perfectly in all releases prior.
- GIF performance is as bad as the original `sxiv` in versions prior to v29. 
- When gifs start playing with v29, the first one plays at it's native dimensions, then subsequent ones render at the correct window size. With that, I'm wondering if [this commit](https://github.com/nsxiv/nsxiv/pull/200) is the culprit.
- I noticed that _sometimes_ it's actually working, but the timing is screwed up compared to prior releases. Prior to v29, if I set `-S 10`, it cycles after 10 seconds. With v29, if it works at all, it'll cycle after a few minutes with the same `-S 10`.

I'm wondering if this is an odd edge-case because I'm running this on a Pi with a pretty low-resolution display. Something in the resizing/zooming logic to match the native resolution/window size. 

Will update with any findings. Thanks!

**Comment by N-R-K** [comment]
> * The issue was introduced with the v29 release. It functions perfectly in all releases prior.

So the faulty commit is somewhere between v29..v28, that narrows things down quite a bit.

> * When gifs start playing with v29, the first one plays at it's native dimensions, then subsequent ones render at the correct window size. With that, I'm wondering if [this commit](https://github.com/nsxiv/nsxiv/pull/200) is the culprit.

Can't reproduce this either. Also by "first one" do you mean the first frame or the first image ?

> I'm wondering if this is an odd edge-case because I'm running this on a Pi with a pretty low-resolution display. Something in the resizing/zooming logic to match the native resolution/window size.

That probably has something to do with the issue.

Only commits between v29..v28 which looks sus are e777adf and 0f3766e. Try `git revert`ing them and see if that's the case or not.

P.S: I don't think we've worked on improving gif performance. Atleast not directly, I suspect it might be due to e777adf but that kinda doesn't make too much sense since we have our own internal gif loader and don't rely on imlib2 for loading gifs.

**Comment by 083750043** [comment]
Looks like [0f3766e](https://github.com/nsxiv/nsxiv/commit/0f3766eaaba949bc2eac276cb0a08e0195c17441) was the culprit! Timing and advancing is working fine after reverting, with the aforementioned significant drop in playback performance. 

If you're not able to reproduce it, it's almost certainly due to running this on such an underpowered system.

**Comment by N-R-K** [comment]
Aright, thank for hunting this down. I think I have an idea on why this is happening and how to "emulate" the issue. I'll do some testing and open a PR fixing it in a bit.

**Comment by 083750043** [comment]
Awesome, thanks so much!
