### ISSUE TITLE
miscellanous feature requests

### ISSUE THREAD

**Issue by wael444** [nsxiv/nsxiv#283]
+ for `g_first` and `g_n_last`, instead have a `g_first_or_last` to presumably toggle between them.
+ automatically remove anti aliasing on small images (eg. 96x96 or more)
+ confirm `g_remove_image` via dmenu(1) or another form such as a script in examples/
+ if the image isn't zoomed to a point where it isn't above the width and height of the nsxiv window, automatically go to the next/previous image depending on the action.
+ ( i know these are achieveable via `g_prefix_external` but it'd be nice to have) be able to copy images
+ ~~`g_zoom` automatically changes `thumb_sizes` to increase the thumb sizes upon zooming in more than the limit. / thumb_sizes` on the fly.~~ figured out too late that this is already possible.
+ `i_alternate` to apply on marked images
+ automatically play gifs via an option in `config.h`
+ in mouse, theres keybinds for thumbnail and image, could that be the same for keyboard keybinds? (global has to stay too)

i do not know C, so i cannot implement these myself.
apologies if these do already exist and i just don't know.

**Comment by N-R-K** [comment]
> * for `g_first` and `g_n_last`, instead have a `g_first_or_last` to presumably toggle between them.

You can use <kbd>G</kbd> to jump to the last image, and <kbd>g</kbd> to jump to the first.

> * automatically remove anti aliasing on small images (eg. 96x96 or more)
> * if the image isn't zoomed to a point where it isn't above the width and height of the nsxiv window, automatically go to the next/previous image depending on the action.

Could you describe what the usecase for these are?

> * confirm `g_remove_image` via dmenu(1) or another form such as a script in examples/

Don't think it makes sense to do it via external tool. Maybe a prompt at the statusbar asking for confirmation, but then again the statusbar can be compiled out or disabled at runtime. So maybe not.

> * ( i know these are achieveable via `g_prefix_external` but it'd be nice to have) be able to copy images

This is definitely not happening. nsxiv is an image-viewer, not a file manager.

> * `i_alternate` to apply on marked images

Hmm... didn't even know that this existed. And the keybinding for it (<kbd>Ctrl+6</kbd>) doesn't seem to be documented in the manpage either.

> * automatically play gifs via an option in `config.h`

There was a discussion about this. The problem was that it would turn cli option `-a` into a no-op when enabled. You could use a wrapper script like [nsxiv-env](https://github.com/nsxiv/nsxiv-extra/blob/master/scripts/nsxiv-env/nsxiv-env) to have a default set of cli args.

> * in mouse, theres keybinds for thumbnail and image, could that be the same for keyboard keybinds? (global has to stay too)

We had to separate the thumbnail and image mode mouse binding for some internal reasons. For keybindings, all the commands prefixed with `g_` applies globally, `t_` only on thumbnails mode and `i_` only on image mode.

You can bind any of the global commands to just a single mode by specifying the mode manually. For example, this would turn `q` into a thumbnail only binding.

```diff
diff --git a/config.def.h b/config.def.h
index 1e102fe..fd26341 100644
--- a/config.def.h
+++ b/config.def.h
@@ -82,7 +82,7 @@ static const KeySym KEYHANDLER_ABORT = XK_Escape;
 /* keyboard mappings for image and thumbnail mode: */
 static const keymap_t keys[] = {
 	/* modifiers    key               function              argument */
-	{ 0,            XK_q,             g_quit,               0 },
+	{ 0,            XK_q,             {cg_quit, MODE_THUMB},               0 },
 	{ 0,            XK_Return,        g_switch_mode,        None },
```

**Comment by wael444** [comment]
Thanks for your comment.

> You can use G to jump to the last image, and g to jump to the first.
I know, but it'd still be nice.

> automatically remove anti aliasing on small images (eg. 96x96 or more)

Usecase for this is for pixel art. anti aliasing is terrible on it.
Least thing possible is to add a flag.

>if the image isn't zoomed to a point where it isn't above the width and height of the nsxiv window, automatically go to the next/previous image depending on the action.

What i mean by this is for images that dont take up the full width of the nsxiv window, can just be ignored by the move keybind and can go to the next. I don't know how else to explain it but i don't think its needed anymore.

> This is definitely not happening. nsxiv is an image-viewer, not a file manager.

Fair. i will try to do this via the external scripts.

> Hmm... didn't even know that this existed. And the keybinding for it (Ctrl+6) doesn't seem to be documented in the manpage either.

> There was a discussion about this. The problem was that it would turn cli option -a into a no-op when enabled. You could use a wrapper script like [nsxiv-env](https://github.com/nsxiv/nsxiv-extra/blob/master/scripts/nsxiv-env/nsxiv-env) to have a default set of cli args.

Alright.

> You can bind any of the global commands to just a single mode by specifying the mode manually. For example, this would turn q into a thumbnail only binding.

Thank you for letting me know about this.

**Comment by 0ion9** [comment]
For pixel art, I implemented a 199% zoom threshold, above which AA is automatically turned off.. if the AA mode is set to auto, which is a third mode I added.
I've had no issues with this personally, interpolation looks pretty bad outside of that small 101%..199% range of scaling, so i don't find any disadvantage in limiting it.

**Comment by wael444** [comment]
https://github.com/nsxiv/nsxiv/blob/b4268fbf38d1f8433c73999466e116e68c7f81e7/config.def.h#L93

**Comment by 0ion9** [comment]
> > For pixel art, in my sxiv fork, I implemented a 199% zoom threshold, above which AA is automatically turned off.. if the AA mode is set to auto, which is a third mode I added.
> 
> I didn't think it would be a good idea to automatically turn AA on/off. But if it's something that the user has to manually opt-in, e.g via config.h like you described, then I dont have any objection towards it.

Opt in is by keybind or config.h ( though with the threshold set at that particular value, it seems to me to be more 'opting out of pointless and ugly blur')

**Comment by wael444** [comment]
shall this be closed?

**Comment by N-R-K** [comment]
> Opt in is by keybind or config.h

Hmm, didn't think this through. What happens in your fork when someone presses <kbd>a</kbd> ? Does it simply do aa `on <=> off` ? or does it cycle between `on => off => auto => on ...` ?

> shall this be closed?

If you think your issues have been addressed, then sure go ahead.

**Comment by 0ion9** [comment]
> > Opt in is by keybind or config.h
> 
> Hmm, didn't think this through. What happens in your fork when someone presses a ? Does it simply do aa `on <=> off` ? or does it cycle between `on => off => auto => on ...` ?

The latter. toggle_antialiasing becomes cycle_antialiasing. So there's no loss of functionality, only slight increase in complexity.
