### ISSUE TITLE
show image from url

### ISSUE THREAD

**Issue by Monirzadeh** [nsxiv/nsxiv#290]
please add option to open image from url something like this
```
nsxiv $imageurl
```

**Comment by N-R-K** [comment]
You can use a script for that.
https://github.com/nsxiv/nsxiv-extra/tree/master/scripts/nsxiv-url

**Comment by N-R-K** [comment]
Also note that we will eventually add pipe support once imlib2 supports loading images from memory (see #32), which would allow doing something like `curl https://url.com | nsxiv` without needing a wrapper script.

However directly opening url is never going to happen. nsxiv is an image viewer, it has absolutely no business connecting to the internet.
