### ISSUE TITLE
Gamma command line option not showing initially

### ISSUE THREAD

**Issue by N-R-K** [nsxiv/nsxiv#30]
Reported by @chrjen in https://github.com/muennich/sxiv/issues/410

> I am using version `sxiv 26`.
> 
> Using the `-G` command line option, e.g. `sxiv -G 30 image.png`, to set the gamma nothing really happens initially. The image looks the same as without that argument. However looking the bottom bar it does says `G+30` and using the `{` or `}` key to manually control the gamma afterwards does work and it "jumps" to either `G+29` or `G+31`. So it is setting the gamma value, but it doesn't seem to be using it initially.

**Comment by eylles** [comment]
closed by https://github.com/nsxiv/nsxiv/commit/ba0468b33478eec19349fb010ea8850c82025edb
