### ISSUE TITLE
Feature request: dmenu mode

### ISSUE THREAD

**Issue by eylles** [nsxiv/nsxiv#38]
As of now sxiv can use the -o option to print out the names of selected files to stdout, that is already very close to dmenu operation but rather clunky by comparison and not quite there yet.

In that regard we can have a more proper dmenu mode even than the already existing patch, but we have to take in design considerations and define behaviours.

How does a proper "visual" dmenu mode works, if we think 1:1 to dmenu the existing patch already does just that, print out the only selected option to stdout when the enter key is pressed and exit dmenu, in our case sxiv it will print the name of the current image however that ignores marked images.

On the other hand sxiv's -o option will print out the names of marked images to stdout, then you need to hit q to exit but it doesn't print out the current image, only marked ones.

Then wehave another interesting semi-overlapping of functionality, the key handler, when pressing ctrl-x and a key (or key chord) sxiv will run the key handler with either the current image or all maked images as arguments.

For such feature to work we have as of now a couple paths to take:
1) a new function with a flag like the one from the dmenu patch
2) overhaul -o option to improve it
3) like one but instead have it as a keybind (like @explosion-mental 's fork)
4) a modified version of the code that calls the keyhandler but instead of calling the keyhandler it prints the list of files to stdout.

We need to take into consideration what the proper behaviour of the dmenu mode should be before deciding which route to take.
Personally i think we may be better of improving the already existing -o option and adding the necesary keybinds to make it work even more like a dmenu.

**Comment by N-R-K** [comment]
>  if we think 1:1 to dmenu the existing patch already does just that, print out the only selected option to stdout when the enter key is pressed and exit dmenu

This is not true. Dmenu has multiple selections by using <kbd>ctrl+enter</kbd>.

Try this `seq 50 | dmenu` and press <kbd>ctrl+enter</kbd>, see what happens.

**Comment by eylles** [comment]
Well, that being the case it seems an overhaul of `-o` may be the way to go...
I get you want to familiarize with the codebase more and i think it is important we all do, however i think discussing what a feature has to do before beggining to look on how to implement it has some merit to it.

**Comment by N-R-K** [comment]
My plan is to leave `-o` as is, and use `-O` instead for dmenu like mode.

**Comment by eylles** [comment]
Fair enough.

**Comment by N-R-K** [comment]
Closing per https://github.com/nsxiv/nsxiv/pull/42

Also see: https://github.com/nsxiv/nsxiv-extra/blob/master/patches/dmenu-mode
