### ISSUE TITLE
Should we move source files to `src/`?

### ISSUE THREAD

**Issue by XPhyro** [nsxiv/nsxiv#44]
The root directory is quite crowded. Should we move source and header files (except maybe the generated `config.h`) to `src/`, like the `exec/` directory for shell scripts?

If so, we should do it before #9 is merged, or maybe in #9.

**Comment by N-R-K** [comment]
> Should we move source and header files (except maybe the generated `config.h`)

If we move, move everything.

**Comment by N-R-K** [comment]
Hmm, do we move `Makefile` into `src/` too? Don't think that's the convention.

**Comment by XPhyro** [comment]
I think Makefile stays in the root.

**Comment by XPhyro** [comment]
@TAAPArthur

**Comment by N-R-K** [comment]
> If so, we should do it before #9 is merged, or maybe in #9.

Let's do it in the rename PR, otherwise rebasing on another PR/branch sounds like a good way get a shitload of git conflicts.

> I think Makefile stays in the root.

It's more conventional, yeah. We'll have to touch the makefile though.

Also if we move sources to `src/` should objects be generated on `obj/` too?

**Comment by XPhyro** [comment]
> Also if we move sources to `src/` should objects be generated on `obj/` too?

I don't have a preference for that as I always `make clean`. Is there a convention for it?

**Comment by N-R-K** [comment]
> Is there a convention for it?

I think that's what typically happens. But putting that aside, I can think of one _actual_ benefit of doing this. When we do `src/op` and hit <kbd>tab</kbd> it'll autocomplete straight to `src/options.c` since there's no `*.o` variant.

**Comment by GRFreire** [comment]
I think that the rename PR and this are not in the same scope, but it is indeed much simpler (so we don't get lots of git conflicts). So I'm fine in doing this inside that branch. Completely in favor of moving files to `src/` and `obj/`

**Comment by N-R-K** [comment]
We can also do it AFTER the rename pr gets merged. That way we wont get conflicts. Also since we're merging to `dev` it shouldn't matter weather we do it before or after the rename PR.

**Comment by TAAPArthur** [comment]
> > I think Makefile stays in the root.
> 
> It's more conventional, yeah. We'll have to touch the makefile though.

Technically we could more the Makefile to src and have a new one in root that just calls into it. I don't have a preference on this specific matter; just stating an option.

Personally not eager to move things to a sub directory. I don't really see the benefit as most of the interesting files will just move to src. I don't have a strong reason to object although it is marginally more convenient for me to have the config.h in the root directory.

@XPhyro Out of curiosity is this cosmetic to you or does it make hacking easier for you?

**Comment by N-R-K** [comment]
> Technically we could more the Makefile to src and have a new one in root that just calls into it. I don't have a preference on this specific matter

We'll still have to touch the makefile since `install` looks into `exec` which will be in the root directory.

One benefit other than cosmetic preference is that we will have a clean source directory without any objects, so that can make tab completing easier. But is that a high enough return on the effort that will need to invested into this? Probably not.

I'm fine either ways we go.

**Comment by XPhyro** [comment]
> @XPhyro Out of curiosity is this cosmetic to you or does it make hacking easier for you?

It is _slightly_ easier to hack on.
- As N-R-K pointed out, this change will allow better tab-completion
- Tools like `fzf` can be used more effectively as it will not search through other clutter
- Terminal file managers such as `lf` can be used more effectively as you will not have to navigate through other clutter

And also, cosmetic reasons:
- It looks better on GitHub and you do not have to scroll 3-4 strokes to get to the readme
- It looks better in terminal and graphical file managers

**Comment by N-R-K** [comment]
So what's the verdict on this? While I see a couple benefit, I don't believe they justify the effort. Personally I don't want to put any energy onto this, since @XPhyro and @GRFreire are interested, could you guys put together a prototype and open a PR?

**Comment by GRFreire** [comment]
Should all imports have a `src/` prefix on them or should the base directory be the `src`? If the second one is the best way to go, how would a file import something outside `src`, say `icon/data.h` for example? I think that `../` is ugly when including stuff.

**Comment by XPhyro** [comment]
@GRFreire I think we can just move `data.h` into `src`.

**Comment by N-R-K** [comment]
Imo, `../` is fine.

**Comment by N-R-K** [comment]
Closing, since we couldn't find any sane way to do this POSIX-ly. See: https://github.com/nsxiv/nsxiv/pull/81
