### ISSUE TITLE
Feature request: Add checked pattern window background

### ISSUE THREAD

**Issue by Dupond** [nsxiv/nsxiv#58]
Hello,
I'm super happy to see this fork! I read the issues and pull requests for a week, and thought maybe I could suggest a few ideas while you're at it ;)

1. The PR #23 is a great step, but I'd hope a fully customizable window title; that would also allow to hide the info bar at startup, and have a clean - yet useful - interface: for example, it'd be really nice to be able to set the title as "image_fullname (zoom_level %) - nsxiv (image_index / total_number_of_images)".
2. It would be nice to add an option (maybe -R) to randomize the slideshow; that would also be a non-breaking change;
3. I'm not sure about the issue #50: would that mean that any undefined pressed key would be passed to the key-handler? That would be amazing!
4. The only feature that feh has and that I'd really like to see implemented in nsxiv is the checked pattern background (or do we call it a tartan? Sorry for my bad english) For me, it's the only viable option, since sometimes the images have a dark background, and sometimes they have a light background, so it's either that, or we would need an option to change the background color on the fly, so that you can always see your image limits.
5. Last but not least, I'm not sure I understand why libexif is an optional dependency: does sxiv have the ability to display exif informations? That'd be super helpful too (and yet another non-breaking change).

I don't know if you'll care at all, but anyway, thanx for the work being done, and long live nsxiv!

**Comment by N-R-K** [comment]
Hi, thanks for the feedback. Randomizing slideshow seems like a good feature to have. I can see check background being useful as well.

As for 1, sxiv shows all those information in the statusbar already and you can customize it further via `image-info` (please see the manpage for further info). As for libexif, I'm not totally sure but it seems we're using it for auto orientation and thumbnails.

**Comment by Ytrewq13** [comment]
Making the background chequered would (maybe) require an overhaul of the way we render images, as in the `img_render()` function in `image.c` we generate a blank background for any image with transparency. I think enabling the 'Alpha layer' setting changes this. Rendering thumbnails has a similar problem I think. Such an overhaul is required, as we also have the issue with animations spiking the CPU usage when they reset to the first frame.

**Comment by eylles** [comment]
>
>4. The only feature that feh has and that I'd really like to see implemented in nsxiv is the checked pattern background (or do we call it a tartan? Sorry for my bad english) For me, it's the only viable option, since sometimes the images have a dark background, and sometimes they have a light background, so it's either that, or we would need an option to change the background color on the fly, so that you can always see your image limits.

we already have that, all you need to do to turn the checkered background on is pres `A`

![Screenshot at 2021-09-16 13-48-25](https://user-images.githubusercontent.com/33670677/133677103-32acb44d-8673-4b04-ad89-5d64c4ea9984.png)

**Comment by XPhyro** [comment]
> we already have that, all you need to do to turn the checkered background on is pres `A`

You can also set `ALPHA_LAYER` to `true` in `config.h` to change the default behaviour.

-----

I feel like this is not what was requested:

> since sometimes the images have a dark background, and sometimes they have a light background

Having a background suggests that the image is not transparent and that @Dupond would like to  have the nsxiv background (i.e. the one that can be set in Xresources) be chequered.

**Comment by eylles** [comment]
well it is all about wording, the way the suggestion was worded i interpreted it as the alpha layer.

**Comment by Dupond** [comment]
Thank you everyone for all the explanations!

> Having a background suggests that the image is not transparent and that @Dupond would like to have the nsxiv background (i.e. the one that can be set in Xresources) be chequered.

That's exactly what I meant, thanx or the rewording ;) I think that would really be a nice feature... but might be hard to implement, as Ytrewq13 explains.

Does anyone know if I was right about my number 3? My understanding of #50 was that any key that wouldn't be defined in `config.def.h` or `config.h` would be passed to the key-handler, am I right?

Thanx to all the contributors of this new project! I had tried a few "improvements" (from my point of view, at least) of sxiv by myself, but they seem buggy... I'm a really bad programmer, unfortunately. Keep up the good work!

**Comment by N-R-K** [comment]
> My understanding of #50 was that any key that wouldn't be defined in `config.def.h` or `config.h` would be passed to the key-handler, am I right?

I don't believe so. I think it's referring to functions within nsxiv.

**Comment by TAAPArthur** [comment]
> > My understanding of #50 was that any key that wouldn't be defined in `config.def.h` or `config.h` would be passed to the key-handler, am I right?
> 
> I don't believe so. I think it's referring to functions within nsxiv.

@Dupond I think you intuition is correct. Instead of the hard coded list of functions, I was going to allow users to specify any arbitrary function. So in your config file you could specify an arbitrary function that takes an arg_t and can do anything you want including calling other nsxiv functions or spawning an external program. So you can basically map keys to anything you want but you would still need to create the function in your config file.

**Comment by N-R-K** [comment]
> but you would still need to create the function in your config file.

Yeah, that's what I meant. Creating a function inside config is still _within_ nsxiv, not being passed to keyhandler.

**Comment by TAAPArthur** [comment]
>It would be nice to add an option (maybe -R) to randomize the slideshow; that would also be a non-breaking change;

I imagine the implementation would be the same as if the input list was randomized. If so then this could be done fairly easily with a wrapper. One could just walk all arguments and replace any directories with a list of their immediate children that are files and then shuffle said list and pass into nsxiv.

**Comment by N-R-K** [comment]
Looks like muennich was against adding shuffle into sxiv as well. https://github.com/muennich/sxiv/pull/227

```sh
find -L . -maxdepth 1 -type f -iregex '.*\.\(jpe?g\|png\|gif\|webp\|tiff\|bmp\)$' -print | shuf | nsxiv -i -S 2
```
@Dupond can you try this and confirm that it takes care of your usecase (2)?

**Comment by GRFreire** [comment]
I've created a script that takes care of this randomization thing. Its available in the wiki.

Just one thing that is kinda badly written is `tr ' ' '\n' | shuf | tr '\n' ' '`.
One could theoretically pass `-e` to `shuf` and dont need this, but it was not working. (Also dont know if that flag is posix).

Any feedback on that wrapper script would be appreciated.

**Comment by N-R-K** [comment]
Imo, since it has massive amount of duplicate codes from the other scripts, I've added that as a one liner `tips and tricks` instead. @GRFreire

**Comment by GRFreire** [comment]
> Imo, since it has massive amount of duplicate codes from the other scripts, I've added that as a one liner `tips and tricks` instead.

I agree that it does have a lot of duplicate code, but idk if the best approach is to have one script, and all others that have different use-cases but similar code just be mentioned (the changes) somewhere. If the use-case was similar, then I would agree with you. 

About the one liner that you added, afaik it only works randomizing the pictures inside the current directory. The script I've added handles both pictures paths as well as paths to directories which contains images. Not a lot of difference, but guessing how to do this only with the one liner given isn't trivial.

> Also the entire `tr` thing was unneeded (not to mention, that it wouldn't work on files with spaces in the name, which are quite common)

Haven't thought about those, surely something that I need to add (at least on my script)

> simply changing `sort` to `shuf` inside `listfiles` on [nsxiv-rifle](https://github.com/nsxiv/nsxiv/wiki/nsxiv-rifle) would've had the same effect but much more sanely.

If you are only opening one directory, yes, but if you are opening multiple pictures and directories, it wont be totally random.

**Comment by GRFreire** [comment]
@N-R-K , I would like a feedback on my [last comment](https://github.com/nsxiv/nsxiv/issues/58#issuecomment-926913618), if possible (since you've taken action before any talking).

**Comment by N-R-K** [comment]
@GRFreire The main reason I removed the script was because it wouldn't work on files with spaces, I didn't want to have faulty scripts in the wiki.

If you can fix that and believe it has value, then feel free to re-add it. Also since we're moving all scripts/patches to [nsxiv-extra](https://github.com/nsxiv/nsxiv-extra), if you do decide to add it I think it'll be better you add it there directly.

**Comment by N-R-K** [comment]
Revisiting this

3 and 5 were questions which I think has been answered. We also updated the README to include what all the optional deps do so there shouldn't be any more confusion about that.

Since 2 can be done easily via a shell script, unfortunately we can't add it to mainline nsxiv. (Feel free to submit a community patch to [nsxiv-extra](https://github.com/nsxiv/nsxiv-extra) )

That leaves us with two feature requests. 1 is to allow fully customizable window title, and 4 adding check window background. Since there's already another issue for customizable window title (https://github.com/nsxiv/nsxiv/issues/97) I'm renaming this issue to the remaining feature request.

**Comment by Dupond** [comment]
Thanx for all the comeback; I haven't had time to read all this before, but thanx very much to all who answered!

**Comment by N-R-K** [comment]
@Dupond Check out [toggle-winbg patch](https://github.com/nsxiv/nsxiv-extra/blob/master/patches/toggle-winbg). It's not checked background like you asked for, but should take care of being able to distinguish the image border.

**Comment by Dupond** [comment]
Hello N-R-K,

Thanx for the patch! But having to patch the code each time I pull changes and recompile is really painful, isn't it? Or is there an easy way to apply it each time the nsxiv code changes?

Maybe an easier way (well, for me) would be to just use a custom function that would sit in my `config.h` only... but would it be feasible?

**Comment by N-R-K** [comment]
> But having to patch the code each time I pull changes and recompile is really painful, isn't it? Or is there an easy way to apply it each time the nsxiv code changes?

Use a separate git branch and rebase your branch on top of mainline. https://dwm.suckless.org/customisation/patches_in_git/

**Comment by XPhyro** [comment]
> Use a separate git branch and rebase your branch on top of mainline. https://dwm.suckless.org/customisation/patches_in_git/

You can couple this with [Git hooks](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) to automatically rebase and compile when you update the nsxiv source. You may also update the nsxiv source periodically with cron.

In this case, the patch can be converted to a config function. See [config-functions/toggle-winbg](https://github.com/nsxiv/nsxiv-extra/tree/master/config-functions/toggle-winbg).

**Comment by Dupond** [comment]
That's an interesting method. Thank you very much for the links, too! I was looking for a way to do this for a long time (for my `st` terminal), but hadn't found it. Thanx for the help, and thanx to N-R-K for the patch!
