### ISSUE TITLE
Add support for animated png images

### ISSUE THREAD

**Issue by Ytrewq13** [nsxiv/nsxiv#65]
We should add support for animated PNG images (APNG).

The specification for APNG is described on [Mozilla's website](https://wiki.mozilla.org/APNG_Specification).

This will be very similar to gif and webp (and multi-page TIFFs if we ever support that) so I'm going to take a look at it myself when I get a chance. If anyone else is already familiar with PNGs or with libpng and wants to take a crack at this, feel free to add yourself as an assignee and start working on a PR for this.

From looking at libpng, it appears there is no easy "get next animation frame" function like libwebp has, so this will probably be more difficult to implement, but several projects have their own implementations of APNG demuxing, so we should be able to take inspiration frfom them (one example is [apngdis](https://sourceforge.net/projects/apngdis/)).

**Comment by N-R-K** [comment]
Closing, see: #193

**Comment by N-R-K** [comment]
Imlib2 [v1.8.0](https://sourceforge.net/p/enlightenment/mailman/message/37605728/) added support for multi-frame images, which includes apng. nsxiv doesn't use the Imlib2 multi-frame api yet, but there's a PR open for that, just needs some minor polishing and bugfixes: #198
