### ISSUE TITLE
Thumbnail mode crashes: cannot allocate memory

### ISSUE THREAD

**Issue by N-R-K** [nsxiv/nsxiv#69]
Reported by @kristianlm in https://github.com/muennich/sxiv/issues/433

Also related issue: https://github.com/muennich/sxiv/issues/325

> Hi,
> 
> I'm getting the same error as #325 so this may be a duplicate. I think I have managed to narrow things down to a image-metadata problem on a single `jpg` (attached below). I'm on Arch Linux. Here we go:
> 
> ```shell
> > sxiv -v
> sxiv 26
> > pacman -Qi sxiv | grep Version
> Version         : 26-1
> > pacman -Qi imlib2 | grep Version
> Version         : 1.7.1-1
> > sxiv bad.jpg
> # [image shows up OK, but then I press enter]
> sxiv: Cannot allocate memory
> > ll
> total 2.5M
> -rw-r--r-- 1 klm klm 2.5M Jan 14 14:15 bad.jpg
> > convert bad.jpg -resize 1% -quality 1% bad-small.jpg
> > sxiv bad-small.jpg
> # [same symptom: image shows up OK, but then I press enter]
> sxiv: Cannot allocate memory
> # trying now with the image metadata stripped off
> > convert bad.jpg -strip -resize 1% -quality 1% bad-small-stripped.jpg
> > ll
> total 2.5M
> -rw-r--r-- 1 klm klm 2.5M Jan 14 14:15 bad.jpg
> -rw-r--r-- 1 klm klm  13K Jan 14 14:16 bad-small.jpg
> -rw-r--r-- 1 klm klm  309 Jan 14 14:16 bad-small-stripped.jpg
> > sxiv bad-small-stripped.jpg
> # now things are working!
> # examining bad-small.jpg with exiv2 shows a warning, perhaps this could be the sinner right there?
> > exiv2 bad-small.jpg
> Warning: Directory Thumbnail, entry 0x0201: Data area exceeds data buffer, ignoring it.
> File name       : bad-small.jpg
> File size       : 12597 Bytes
> MIME type       : image/jpeg
> Image size      : 26 x 19
> Camera make     : Apple
> Camera model    : iPhone 4
> Image timestamp : 2015:11:01 14:52:35
> Image number    : 
> Exposure time   : 1/15 s
> Aperture        : F2.8
> Exposure bias   : 
> Flash           : No, auto
> Flash bias      : 
> Focal length    : 3.8 mm (35 mm equivalent: 35.0 mm)
> Subject distance: 
> ISO speed       : 1000
> Exposure mode   : Auto
> Metering mode   : Multi-segment
> Macro mode      : 
> Image quality   : 
> Exif Resolution : 2592 x 1936
> White balance   : Auto
> Thumbnail       : None
> Copyright       : 
> Exif comment    : 
> 
> # nobody was expecting anything here, but for completeness:
> > exiv2 bad-small-stripped.jpg 
> File name       : bad-small-stripped.jpg
> File size       : 309 Bytes
> MIME type       : image/jpeg
> Image size      : 26 x 19
> bad-small-stripped.jpg: No Exif data found in the file
> ```
> 
> This is the faulty image:
> ![bad-small](https://user-images.githubusercontent.com/259445/104596953-ff0a6b00-5674-11eb-8275-6afae4992873.jpg)
> 
> I hope you guys can get an unmodified copy back from github. It should look like this:
> 
> ```shell
> > sha1sum bad-small.jpg 
> d1f2440a61ea8fb00003388464483f04b6a3e5ce  bad-small.jpg
> ```
> 
> Since #325 was closed, and possibly had a different cause, I though I'd create a new issue. Thanks for the sxiv suite!

**Comment by N-R-K** [comment]
This seems like an issue with bad exif data, when compiled with `HAVE_LIBEXIF=0` things work just fine.

Here's the offending line

https://github.com/nsxiv/nsxiv/blob/24e70a99e38ba71ac26e8476c5f2d4352c6ff548/thumbs.c#L314

**Comment by N-R-K** [comment]
```diff
                                                if (w >= maxwh || h >= maxwh) {
                                                        if ((im = imlib_create_cropped_image(x, y, w, h)) == NULL)
-                                                               error(EXIT_FAILURE, ENOMEM, NULL);
+                                                               error(0, 0, "Bad exif data: %s", file->name);
                                                }
```

Simply changing this to a non-fatal error seems to work fine. If `im` is NULL we're loading with imlib2 anyways here:
https://github.com/nsxiv/nsxiv/blob/24e70a99e38ba71ac26e8476c5f2d4352c6ff548/thumbs.c#L327-L330

@bakkeby Can you see any potential side-effects this may cause?

**Comment by bakkeby** [comment]
As far as I can see the proposed change looks perfectly fine. As `im` is `NULL` it will be opened as normal as you say, and it would have gone down that path anyway if the user did not have `HAVE_LIBEXIF` enabled.

If the error is fatal does that not mean that `tmppath` would be leaving a file under /tmp/ given that we do not reach the unlink at line [319](https://github.com/nsxiv/nsxiv/blob/24e70a99e38ba71ac26e8476c5f2d4352c6ff548/thumbs.c#L319)?

If so then it is more correct anyway to have this as a non-fatal error.

**Comment by N-R-K** [comment]
> If the error is fatal does that not mean that `tmppath` would be leaving a file under /tmp/ given that we do not reach the unlink at line [319](https://github.com/nsxiv/nsxiv/blob/24e70a99e38ba71ac26e8476c5f2d4352c6ff548/thumbs.c#L319)?

You're correct, that tmpfile never gets cleaned.
