### ISSUE TITLE
Animations slowdown when zoomed in

### ISSUE THREAD

**Issue by N-R-K** [nsxiv/nsxiv#70]
Reported by @yaomtc in https://github.com/muennich/sxiv/issues/460

> It's like half the speed. This is on a 1440p display with an RX 5700 XT.

**Comment by Ytrewq13** [comment]
This sounds like it would be related to the issue with rendering that we discussed in #20. If we overhaul how frames are rendered to fix the CPU spikes, I think we would also be addressing this issue at the same time.
I'm not going to have time to attempt this any time soon, as it's a much larger change than what I've been doing so far. I'll try to recreate the issue by making a high fps animation in a couple of resolutions to discover more about what causes it in the meantime.
(A note: this will probably be unrelated to GIF vs WebP as they both should have the same internal representation once they are loaded into an `img_t` struct. I'll also test this)

**Comment by N-R-K** [comment]
About that, I think I forgot to mention. I was able to get those spikes on a couple `gif` file as well. So it's not a regression added by the animated-webp patch.

**Comment by eylles** [comment]
So the cpu usage spikes ain't truly something with webp but rather a problem from the innards of sxiv...

**Comment by DusanLesan** [comment]
The gif-s are not playing at all for me now. Near original sxiv is working ok.

**Comment by N-R-K** [comment]
@DusanLesan Can you describe how you installed nsxiv? Was it through a package manager or manually?

**Comment by DusanLesan** [comment]
@N-R-K Sorry, my bad. I have not followed instructions from readme. I have habit to just run `sudo make clean install` for all suckles software and sxiv. That worked for sxiv but not here. I'll be more careful in future.

**Comment by N-R-K** [comment]
This might be related https://github.com/muennich/sxiv/issues/132

**Comment by N-R-K** [comment]
Hmm, the way we're dealing with animation is by setting a timeout and checking it at the beginning of the loop in `run()`. Might be a good point investigate.

Although that doesn't explain why the slowdown occur only when zoomed in.

---

Also found this comment https://github.com/derf/feh/issues/18#issuecomment-918141199 which might be related.

> sxiv is unable to play animations with very little delay between frames (dunno, <30ms ?) at correct speeds

One more thing to note: we're sleeping for 10ms inside run.

https://github.com/nsxiv/nsxiv/blob/c6275374b03ac4526a46f255f33ae2f81003d52b/main.c#L768-L770

**Comment by N-R-K** [comment]
Aright, none of the things I've said above are related. The real reason animation slows down is 3 fold

* Imlib2's alpha rendering seems to be slow. However this is not too important because we have an optimized path for bypassing it, see: https://github.com/muennich/sxiv/issues/132
* Imlib2's scaling is slow.
* Anti-aliasing is REALLY slow.

Here's some benchmark result:

| Path | 100% zoom, no AA | 1600% zoom, no AA | 1600% zoom with AA |
| --- | --- | --- | --- |
| Optimized alpha path enabled   | 0.15~  | 1.8~2.0  | 6.1~6.2 | 
| Optimized alpah path disabled   | 0.33~  | 2.5~2.6  | 6.9~7.0 |

**Comment by yaomtc** [comment]
Would it be possible for anti-aliasing to be disabled for animated GIFs? Seems like it'd be an easier/quicker workaround than completely replacing imlib2... which seems to have been considered deprecated by its maintainers (Enlightenment) for a decade now.

**Comment by N-R-K** [comment]
> Would it be possible for anti-aliasing to be disabled for animated GIFs?

That would lead to bad image quality when zoomed in.

Also you can manually disable anti-aliasing with the keybinding <kbd>a</kbd>
