### ISSUE TITLE
Packaging nsxiv

### ISSUE THREAD

**Issue by N-R-K** [nsxiv/nsxiv#72]
Now that we have an official release, it would be great if users can package nsxiv for their distro and add it to their respective community repo.

Currently nsxiv is available on the following distros

- - -

- [x] Gentoo (GURU overlay)
- [x] Arch/Artix (AUR) - maintainer: @WitherCubes
- [x] Void - maintainer: @WitherCubes
- [x] FreeBSD ports
- [x] [Fedora Copr](https://copr.fedorainfracloud.org/coprs/mamg22/nsxiv)

- - -

If you have packaged nsxiv, then please leave a message here. We will include all the distros/repos which contain nsxiv in our README.

**Comment by WitherCubes** [comment]
I packaged nsxiv in the AUR (Arch Linux User Repository). Here is the link - https://aur.archlinux.org/packages/nsxiv

**Comment by N-R-K** [comment]
On that topic should we use the repology badge in the README instead of manually adding them? It would look like the following:

[![Packaging status](https://repology.org/badge/vertical-allrepos/nsxiv.svg)](https://repology.org/project/nsxiv/versions)

In markdown:

```markdown
[![Packaging status](https://repology.org/badge/vertical-allrepos/nsxiv.svg)](https://repology.org/project/nsxiv/versions)
```

This means we won't have to manually track which distro packaged it and it can automatically track the version too.

**Comment by eylles** [comment]
yeah, it seems like a good thing to do.

**Comment by N-R-K** [comment]
After it's been packaged for a couple more distros, we can add it to the readme then. Until then let's keep this issue open/pinned so that people interested see this.

**Comment by WitherCubes** [comment]
I have made a pull request in the void-packages repo for Void Linux. I don't know if they will accept the pull request. If not we should fin an another way to package for Void Linux

https://github.com/void-linux/void-packages/pull/33009

**Comment by WitherCubes** [comment]
Hey @N-R-K whet do you think about this:

https://github.com/void-linux/void-packages/pull/33009#issuecomment-923699397

**Comment by N-R-K** [comment]
@WitherCubes I don't think sxiv ever had anything to do with `/usr/share/examples`.
That's a void patch, https://github.com/void-linux/void-packages/blob/75403cef76a93199456befdcb8884fbac39adbb3/srcpkgs/sxiv/patches/sxiv-1.3-makefile.patch

**Comment by WitherCubes** [comment]
nsxiv is added to Void Linux Main Repo. https://github.com/void-linux/void-packages/pull/33009

**Comment by zoj613** [comment]
Is it intentional that `nsxiv` can be installed alongside `sxiv` using the AUR repo? I just discovered this project and im not sure if this can cause problems?

**Comment by eylles** [comment]
Yes, it is intentional, think about it like the picom and compton case, well kinda like it.

**Comment by N-R-K** [comment]
>  I just discovered this project and im not sure if this can cause problems?

`nsxiv` and `sxiv` can be used alongside just fine. It won't cause any problem.

**Comment by zoj613** [comment]
Thanks for the reply. I'm excited to see where this project goes. Is there a page I can read that outlines the additions/differences to `sxiv` as of today? I want to decide if I should uninstall `sxiv` and keep the newer one.

**Comment by eylles** [comment]
Don't worry, there's the [changelog](https://github.com/nsxiv/nsxiv/blob/master/CHANGELOG.md) altho it gets updated for stable releases.

**Comment by mamg22** [comment]
I'm currently working on packaging nsxiv for Fedora, I've already got a spec file based on the one used for the current version of sxiv in the fedora repos, just needed a few changes and some modernization, it works and builds a proper rpm package. I'm still figuring out how to publish it to COPR, but once that's done, it'll be possible to add that COPR repo and install nsxiv with `dnf` as usual.

**Comment by mamg22** [comment]
Ok, getting it published was easier than I expected :D. It succesfully built for Fedora 33/34/35/Rawhide, installed on my machine (F34) and it works. For anyone wanting to test it out, enable the repo with `sudo dnf copr enable mamg22/nsxiv` and install with `sudo dnf install nsxiv`.

The [repo site at COPR is here](https://copr.fedorainfracloud.org/coprs/mamg22/nsxiv/). I still need to give it a good description, installation instructions and some polish to the package metadata.

**Comment by N-R-K** [comment]
@mamg22 Doesn't seem like [repology](https://repology.org/project/nsxiv/versions) is tracking copr, we'll have to manually include that in our README I guess.

@0mp Thanks for packaging on freebsd! Can I ask what the `.20` at the end means?

**Comment by mamg22** [comment]
> seems like copr version don't support webp images… @mamg22

@Tokariew Just tested it with a static webp image and it doesn't work either. I believe it is an issue with Fedora's `imlib2` package, because `feh` can't open it either.

It ships `imlib2` version 1.6.1, which _should_ have WebP support, but the [spec file for it](https://src.fedoraproject.org/rpms/imlib2/blob/rawhide/f/imlib2.spec) doesn't require `libwebp-devel` when building the package, so it is disabled when configuring.

An issue or pull request should be filed in the pagure repo for `imlib2` so the maintainers fix and update the package.
