### ISSUE TITLE
Changing the location of example scripts

### ISSUE THREAD

**Issue by N-R-K** [nsxiv/nsxiv#85]
As discussed here https://github.com/void-linux/void-packages/pull/33009#issuecomment-924334800 , should we change our example script location from `$(DESTDIR)$(PREFIX)/share/nsxiv/exec/` to `$(DESTDIR)$(PREFIX)/share/examples/nsxiv` ?

**Comment by XPhyro** [comment]
I don't have a `*share/examples/` directory on Arch Linux. Is that standard practice Void-specific?

**Comment by N-R-K** [comment]
I don't have a `*share/examples` either ¯\_(ツ)_/¯

**Comment by XPhyro** [comment]
`grep`ped the `srcpkgs/` in that repository. Looks like it is indeed a standard, at least in Void.

I'm okay with changing it, if there is no general standard that conflicts with Void's.

**Comment by paper42** [comment]
> I'm okay with changing it, if there is no general standard that conflicts with Void's.

There is also `/usr/share/doc/<pkgname>/(examples/)` which might be more common across distributions.

**Comment by N-R-K** [comment]
`/usr/share/doc` is more common, yes. But `/usr/share/<pkgname>` , which (n)sxiv currently has, is also common. So I'm not sure if it's worth changing.

**Comment by XPhyro** [comment]
Looked in my `/usr/share` and `/usr/local/share`: apart from a few packages, most of them are located in `doc/`. Examples seem to be located in a sub-directory called `examples`, `util` or `utils`. `doc/*/examples` is by far the most common.

I think we should either change to `doc/nsxiv/examples` or keep it in the same prefix, but put the scripts in a sub-directory called `examples`.

We already changed quite a lot, I don't think it would hurt to change this to match the standard.

**Comment by paper42** [comment]
As I see it
* `/usr/share/doc` is where documentation goes, all other packages on my system use this for documentation, so I look there when I need to look up something
* `/usr/share/<pkgname>` is where functional files go = gedit plugins, vim syntax files, etc. I think that sample config files or documentation should never go there 

This is a new package with a new name, not just an upstream change, so I think you can move some files around, especially when they are just docs. So I would propose something like `/usr/share/doc/nsxiv/examples/`.

**Comment by N-R-K** [comment]
Seems like debian doesn't install the examples at all: https://sources.debian.org/patches/sxiv/25-1/not_install_examples.diff/

I'll look into what some other distros are doing with sxiv. But if we do change, then `share/doc/nsxiv/examples` seems like the best way to go.

**Comment by N-R-K** [comment]
Arch, Gentoo, Nix, Fedora, CRUX and OpenBSD Ports -- all seems to just install them as is, to `share/sxiv/exec`. [OpenSuse](https://software.opensuse.org/package/sxiv) seems to be using XML as their package format ... I'm not gonna bother trying to read that mess.

> Seems like debian doesn't install the examples at all: https://sources.debian.org/patches/sxiv/25-1/not_install_examples.diff/

Debian patches it out of the Makefile so that they can install the examples to somewhere else instead. Not sure where though.

- - -

So we have 2 distros that have taken a problem with the current location so far, Void and Debian. Given that, I think I'm okay changing it.

**Comment by WitherCubes** [comment]
Is the change going to happen for v28 of nsxiv? Until that should I make a patch for it in void?

**Comment by WitherCubes** [comment]
Ok, I will add the patch

**Comment by WitherCubes** [comment]
Added the patch, tested it out and it is working.

https://github.com/void-linux/void-packages/pull/33009/commits/f75cc093da1a223f605c1eaed4b5552d6cf3bf85
