### ISSUE TITLE
Feature Request: Add `thumb-info` similar to `image-info`

### ISSUE THREAD

**Issue by N-R-K** [nsxiv/nsxiv#88]
Reported by @Earnestly in https://github.com/muennich/sxiv/issues/429

> Would it be possible for the `image-info` script to update the status bar when selecting images in thumbnail mode?
> 
> When recovering photographs it would have been useful to see the size or dimentions of the image in order to avoid the recovered thumbnails.
> 
> As an alternative I could use `display -format '%w %h %d/%f\n'` and filter based on those in a script before passing them onto `sxiv`.

**Comment by explosion-mental** [comment]
I've had a quick look at this and moving `close_info(); open_info();` into `tns_move_selection` and also maybe into `switch_mode` seems to do the work.

There is one catch that I discover while working on `mage` and got into a dilema. Since sxiv has two 'modes' it also loads them separetly, if it's **image_mode** it only loads the current image (when moving, it loads the next one and 'deloads' the previous). However, on **thumbnail_mode** it loads a 'stack' (rows * cols) of images.

The point is that the following code on `open_info()`:
```c
		snprintf(w, sizeof(w), "%d", img.w);
		snprintf(h, sizeof(h), "%d", img.h);
```
indicates to use the `img.w` and `img.h`, meaning when moving throught **thumbnail_mode** the dimentions that show on the bar will be the same for all images.
The `filesize` part on the bar works fine, since it's an external program (du).

**Comment by N-R-K** [comment]
One more thing, I don't think it's a good idea to apply `image-info` to thumbnail mode since it'll somewhat break the visuals.

Instead we can have `thumb-info` which would work exactly the same way as `image-info`, this would allow users to have different script depending on thumbnail vs image mode. And if someone wants the same thing, he can use a symlink.

**Comment by explosion-mental** [comment]
hmm Im not too sure but we could store the 'real size' of the image when loading (or before rezising on thumb_render), say `info_width` and `info-height`. Looks much more simple and I think its a minor change.
No need for another script, although if thats requested we could discuss it?

**Comment by N-R-K** [comment]
> Im not too sure but we could store the 'real size' of the image when loading (or before rezising on thumb_render), say `info_width` and `info-height`.

That's not the reason I suggested a different script. Main reason for it is we don't want the statusbar of users to suddenly change after updating. Not everyone may want `image-info` to be applied to thumbnail view as well.

**Comment by explosion-mental** [comment]
What do you mean by _updating_?
The status bar updates on every image change, I think if u use the reload/restart keybinding the status bar will also update.

> Not everyone may want image-info to be applied to thumbnail view as well.

Yes. The feature request is to apply `image-info` in thumbnail mode tho.

**Comment by N-R-K** [comment]
> What do you mean by _updating_?

Updating to newer nsxiv version.

> The feature request is to apply image-info in thumbnail mode tho.

Which can be done via making `thumb-info` a symlink to `image-info`.

**Comment by explosion-mental** [comment]
dont know whats wrong with my fingers this week..

**Comment by N-R-K** [comment]
> Im not too sure but we could store the 'real size' of the image when loading (or before rezising on thumb_render)

What if we load the thumbnail from cache? I don't think we'll have the original image width/height then. And loading the original image just to get w/h is not an option, the entire point of the cache is to avoid loading bigger original images.

**Comment by explosion-mental** [comment]
> 

Really good point. How would an external script adress this tho?

**Comment by N-R-K** [comment]
I guess we have to abandon this. The issue originally wanted to see the size of the original image in thumbnail mode, but that's not possible if we load thumb from cache.

If anyone knows a good way to solve this, feel free to post suggestion; we can reopen this if we find a decent solution.
