### ISSUE TITLE
Feature proposal: calculating zoom level with a zoom step instead of hard-coded level array

### ISSUE THREAD

**Issue by OliverLew** [nsxiv/nsxiv#90]
Calculate the zoom level by current_level * zoom_step for zoom in and current_level / zoom_step for zoom out.

I have already implemented it in my sxiv fork: https://github.com/OliverLew/sxiv/commit/b18a8424c4cf2749e01308b3f77d5ef6bbe3eede. If this looks good, I can try to port it to nsxiv.

Pros:

- It is _relative_ zoom. Now one can zoom from any mode and back to that exact zoom level, e.g., 67% -> 84% -> 67%
- The code is much simpler.
- With only max/min zoom level and a zoom step required, the zoom will be log-uniform, so we can avoid any bad chosen level array.

**Comment by N-R-K** [comment]
Hi Oliver, since you already have a working prototype, please open a PR. Imo, it's better suited for discussion when code is involved.

**Comment by XPhyro** [comment]
See #92.
